### ISSUE TITLE
Is it possible that we can change preference_fallback_accent_color value during run-time

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#10]
Hi,

Currently, we allow user to switch between the app theme during run-time

    public static void updateTheme(Context context) {
        if (Utils.isDarkThemeEnabled()) {
            context.setTheme(R.style.Theme_App_Dark);
        } else {
            context.setTheme(R.style.Theme_App_Light);
        }
    }

In your `colors_indigo_pink.xml`,

    <color name="accent">#FF4081</color>
    
    <color name="preference_fallback_accent_color">@color/accent</color>

It only support 1 color. Is there any way we can change `preference_fallback_accent_color` during run-time? I wish I can have something like

    <color name="accent">?attr/my_accent</color>

But Android doesn't support such.

**Comment by Gericop** [comment]
Using only XML it is not possible. However, one can override the default PreferenceCategory behaviour to override the textColor attribute of the TextView used by the category layout.

**Comment by Gericop** [comment]
I created a `PreferenceCategoryFix` class which fixes the default behavior (*sets the text color to the accent color defined in the theme*), I will upload it soon, just writing the docs.

**Comment by Gericop** [comment]
Added the fix, check out the end of the *Interesting things* part of the `README.md`.
