### ISSUE TITLE
TimePickerPreference Listener

### ISSUE THREAD

**Issue by mcxinyu** [Gericop/Android-Support-Preference-V7-Fix#100]
How to listener the TimePickerPreference preference  change？

**Comment by Gericop** [comment]
The normal preference change listener will be usable. It's gonna be included in the next release (probably 26.1.0.3), that I'll try to publish on Thursday (sorry, I had a lot of work to do recently).

**Comment by mcxinyu** [comment]
Thank you for your work, and I can contribute to this library as well.

**Comment by Gericop** [comment]
Available since v**26.1.0.3**.
