### ISSUE TITLE
setDivider and setDividerPreferences don't work together

### ISSUE THREAD

**Issue by KubaB** [Gericop/Android-Support-Preference-V7-Fix#105]
This:

```
     public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
          View view = super.onCreateView(inflater, container, savedInstanceState);
          setDividerPreferences(DIVIDER_DEFAULT);
          Drawable drawable = getContext().getResources().getDrawable(R.drawable.line_divider);
          setDivider(drawable);
          return view;
      }
```

results in this:
![screenshot_2017-10-31-16-21-38-604_com example mpccontroller](https://user-images.githubusercontent.com/33259279/32232253-ef2cf31e-be57-11e7-9de9-ddf856e64f01.png)

and this:
```
     public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
          super.onViewCreated(view, savedInstanceState);
          setDividerPreferences(DIVIDER_DEFAULT);
          Drawable drawable = getContext().getResources().getDrawable(R.drawable.line_divider);
          setDivider(drawable);
     }
```

results in this:
![screenshot_2017-10-31-16-21-54-287_com example mpccontroller](https://user-images.githubusercontent.com/33259279/32232588-a7d42da6-be58-11e7-901f-d3418d0e4697.png)

So clearly, setting divider itself works and setting dividerPreferences too, but it seems one cannot use them together.

**Comment by Gericop** [comment]
I'll check it out.

**Comment by KubaB** [comment]
Any progress on this subject?

**Comment by Gericop** [comment]
Yes, I have identified the problem, it will be fixed soon.

**Comment by Gericop** [comment]
Sorry, this will have to be pushed to v27.0.2.1. I've had no time to fix it yet.

**Comment by KubaB** [comment]
thanks for fast fix
