### ISSUE TITLE
Is there any way we can get a better padding value for divider

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#11]
![screenshot_20160117-121827](https://cloud.githubusercontent.com/assets/308276/12375953/05ac277c-bd15-11e5-9fbe-244bf3af3a90.png)

In non material design, you can see proper padding at divider.

I notice you do have code https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/app/src/main/java/android/support/v7/preference/PreferenceFragmentCompatFix.java#L86

However, `parent.getPaddingLeft` and `parent.getPaddingRight` just return 0.

![screenshot_20160117-122639](https://cloud.githubusercontent.com/assets/308276/12375964/b8d68cb6-bd15-11e5-82c4-69509b8d69dd.png)

Is there any way we can get a better padding value for divider?

**Comment by yccheok** [comment]
Sorry for quick post. I just figured out, I can perform the left/ right calculation inside the `for` loop of individual view.

    final int left = view.getPaddingLeft();
    final int right = parent.getWidth() - view.getPaddingRight();

**Comment by Gericop** [comment]
Well, it depends. Actually the padding is not quite right with that list, if you click on one of the items, you see that the highlighted area is not covering the full width of the window, even though it should.

**Comment by yccheok** [comment]
Based on your work, I'm able to produce the following elegant preference. I made some minor tweak on your original work. Thank you!

Here's the outcome so far.

![device-2016-01-17-195736](https://cloud.githubusercontent.com/assets/308276/12377373/cb4cb550-bd56-11e5-8292-e123391cb912.png)

**Comment by Gericop** [comment]
Note, though, that this is not what the material themed preferences look like officially(?). If you check out the Google apps, you'll see that the dividers is neither present above nor below the category elements, but is visible everywhere else. Although, it's totally up to you what you do with your preferences, I just try to mimic the official one :smile:

**Comment by yccheok** [comment]
In fact, Google isn't consistent with their own design. If you went into GMail app Settings, you will not see any dividers. However, when you click on "General settings", full of dividers are there. Hence, I try to come out with my own tweak, which I feel will generate a reasonable pleasant looking experience.
