### ISSUE TITLE
Fix preference-v7 simple problem

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#112]
Simple have a problem
![image](https://user-images.githubusercontent.com/10644057/32987214-119a7eae-cd20-11e7-931b-d51a7d65ea3a.png)

fix after:

        if (savedInstanceState == null) {
            MoreListPreferenceFragment fragment = new MoreListPreferenceFragment();
            FragmentTransaction ft = getActivity().getSupportFragmentManager().beginTransaction();
            ft.replace(R.id.fragment, fragment);
            ft.commitAllowingStateLoss();
        }

https://stackoverflow.com/questions/7469082/getting-exception-illegalstateexception-can-not-perform-this-action-after-onsa

**Comment by Gericop** [comment]
Replaced `commit()` with `commitAllowingStateLoss()` in the sample app.

**Comment by TCQQ** [comment]
Yes.
