### ISSUE TITLE
How to not extends PreferenceFragmentCompatDividers to use PreferenceFragmentCompatDividers

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#115]
Because i have :BaseFragmentCompat.java，i want extends BaseFragmentCompat, but i can't extends PreferenceFragmentCompatDividers in BaseFragmentCompat.java
![image](https://user-images.githubusercontent.com/10644057/32998036-77f6f27e-cdd2-11e7-99b8-29f56a174cdd.png), because some fragment not need "onCreatePreferencesFix"
![image](https://user-images.githubusercontent.com/10644057/32998042-86da7504-cdd2-11e7-8cd6-30e8c13b6da1.png)

**Comment by Gericop** [comment]
What do you use these fragments for? This is intended for the preferences API, not for generic usage. Also, you can just simply override the `onCreatePreferencesFix(...)` in your `BaseFragmentCompat` so you wouldn't have to in the extending fragments.

**Comment by TCQQ** [comment]
I know, but now the problem is that if I inherit "PreferenceFragmentCompatDividers", that means the function code in "BaseFragmentCompat" can not be used

**Comment by Gericop** [comment]
Why can't you extend `PreferenceFragmentCompatDividers` from `BaseFragmentCompat`? What's your use case?

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/33189415-5e6d99b2-d0dd-11e7-97bc-b9ac69c158a6.png)

**Comment by TCQQ** [comment]
Because if extend "PreferenceFragmentCompatDividers" from BaseFragmentCompat, this method will have to be implemented in subclasses, but some subclasses do not need this method
![image](https://user-images.githubusercontent.com/10644057/33189443-98be19ca-d0dd-11e7-9694-9e03eaf97500.png)

**Comment by Gericop** [comment]
Just "implement" the method in your `BaseFragmentCompat` as an empty one and override it wherever you need it. But it seems to me that you try to use this `BaseFragmentCompat` as a generic solution in your app, not just as a settings screen. In this case don't do that. Simply create two "base" fragments: one for the settings and one for the others.

**Comment by TCQQ** [comment]
But java is a single inheritance, if I inherit "PreferenceFragmentCompatDividers" can not inherit "BaseFragmentCompat"

**Comment by Gericop** [comment]
What is the use of `BaseFragmentCompat`?

**Comment by TCQQ** [comment]
At the same time, "BaseFragmentCompat" and other different types of base class associated
![image](https://user-images.githubusercontent.com/10644057/33189738-b12d1fb2-d0e0-11e7-8e61-3e40e8d4d4a8.png)

**Comment by TCQQ** [comment]
"BaseFragmentCompat" further tab and fragment common functions for further package, so that the code style unified

**Comment by Gericop** [comment]
Simply separate this part of the app from the rest. The settings screen is usually considered a completely different world, so you should not create a universal base Fragment that can be used for everything. Keep the current `BaseFragmentCompat` as is, and create a `SettingsFragmentCompat` that extends `PreferenceFragmentCompatDividers` and implement everything in that separately. You should not use `PreferenceFragmentCompatDividers` or `PreferenceFragmentCompat` in `BaseFragmentCompat` because they contain a lot of things you don't need in most of the fragments.

**Comment by TCQQ** [comment]
In before I could use a single line of code to achieve a function, but now I need to add more code to achieve, over time, the amount of duplicate code will continue to grow

**Comment by Gericop** [comment]
The preference lib cannot work as "implements". These are legit classes, not interfaces.
