### ISSUE TITLE
Feedback ColorPickerPreference problem

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#116]
The colors I set in the code are purple and red, but the final color is not correct, what is the reason?

![image](https://user-images.githubusercontent.com/10644057/32999280-ffffd560-cddb-11e7-9b3e-25ead9c85140.png)

![image](https://user-images.githubusercontent.com/10644057/32999286-10d203ae-cddc-11e7-87b4-48742eca8212.png)

**Comment by DreaminginCodeZH** [comment]
Maybe it should be colors instead of color resources.

**Comment by TCQQ** [comment]
I do not understand, for example?

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/32999511-a827a028-cddd-11e7-9260-583541134268.png)
![image](https://user-images.githubusercontent.com/10644057/32999519-b4d3a1c8-cddd-11e7-9e75-1007740befe5.png)

**Comment by TCQQ** [comment]
I click the color button,  not transfer this callback method, what is the reason?

![image](https://user-images.githubusercontent.com/10644057/33000645-5b0eb3d8-cde4-11e7-8136-7aa234d70c04.png)

**Comment by Gericop** [comment]
@TCQQ Use [`setOnPreferenceChangeListener(...)`](https://developer.android.com/reference/android/support/v7/preference/Preference.html#setOnPreferenceChangeListener(android.support.v7.preference.Preference.OnPreferenceChangeListener)) to get notified about changes in the preference value (i.e. the selected color).

**Comment by TCQQ** [comment]
I use this value to distinguish between different colors, right?

![image](https://user-images.githubusercontent.com/10644057/33190231-754a249a-d0e5-11e7-9222-e50ba5ca5bee.png)

**Comment by Gericop** [comment]
Yes, these are ARGB values.

**Comment by TCQQ** [comment]
Thankyou
![image](https://user-images.githubusercontent.com/10644057/33190586-224d1690-d0e9-11e7-97c7-948e97a3775b.png)

**Comment by Gericop** [comment]
Resolve the colors manually with `context.getResources().getColor(...)`.

**Comment by hienhtet** [comment]
hi i need how to change default color when user is choose .. i use these fun setOnSharePreferecneChangeListener(preferecnce,newValue)
i got newValue to change default value

**Comment by Gericop** [comment]
What do you want to do? Sorry, I don't understand.

**Comment by hienhtet** [comment]
sorry i mean when i choose color from colorPickerPreference and change color in colorPickerPreferene [de]([url](url)) 
![screenshot_20171129-215315](https://user-images.githubusercontent.com/22141397/33382856-3cf58642-d550-11e7-90b3-6c071de8e951.png)
i mean user change color in black circle color bro sorry for my eng :D

**Comment by hienhtet** [comment]
private fun updatePreferences(p: Preference) {
        if (p is ColorPickerPreference) {
            var color = p as ColorPickerPreference
            p.color = color.color
            Log.i("color", color.color.toString())
            Log.i("color", "${color.color}")
        } 
    }
first init preference bro but it color.color always return 0

**Comment by TCQQ** [comment]
How to set the initial circle color for color picker?

**Comment by hienhtet** [comment]
yes i mean like that bro  :D

**Comment by TCQQ** [comment]
I have the same problem

**Comment by Gericop** [comment]
You use the standard `android:defaultValue="#88C440"` attribute to set the initial value of the preference which sets the color of the circular widget, too.

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/33385334-48312652-d563-11e7-9c5a-294d2dda7a8e.png)

**Comment by TCQQ** [comment]
Right?
![image](https://user-images.githubusercontent.com/10644057/33385587-ec0b04be-d563-11e7-97ff-44043b466736.png)

**Comment by Gericop** [comment]
You don't need to call `setColor(...)` from the change listener, just return `true` so the preference manager can automatically save the value.

If the value does not get saved, that means that something is wrong with your XML. Copy the relevant part here.

**Comment by hienhtet** [comment]
just here bro thank
        <ColorPickerPreference
            android:dialogTitle="@string/color_picker_default_title"
            android:key="custom_color"
            android:persistent="false"
            android:summary="Very nice color"
            android:title="ColorPickerPreference"
            app:pref_size="small" />

**Comment by hienhtet** [comment]
<ColorPickerPreference
            android:dialogTitle="@string/color_picker_default_title"
            android:key="custom_color"
            android:persistent="false"
            android:summary="Very nice color"
            android:title="ColorPickerPreference"
            app:pref_size="small" />

**Comment by Gericop** [comment]
You see, the problem is pretty simple and obvious. The attribute `persistent` tells the implementation whether the preference should be saved. Since you set this value to `false`, it won't get saved. Remove this attribute (or set it to `true`) and it's gonna work just fine.

**Comment by hienhtet** [comment]
yeach bro now i seee it :D really nice

**Comment by hienhtet** [comment]
Bro TCQQ you can use change color with 
  var hexColor = String.format("#%06X", 0xFFFFFF and newV.hashCode())

**Comment by TCQQ** [comment]
Ok, thank you.
