### ISSUE TITLE
Feedback DateTimePicker Problem

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#124]
Because app theme the primary color and accent color is dynamic ,applied color allows the user to pass in the color code, it is impossible to add all the color values in style, so can only programmatically change the control color dynamically, how to programmatically change DateTimePicker the primary color and accent color?
![image](https://user-images.githubusercontent.com/10644057/33410524-a601b79e-d5bb-11e7-9ebb-4231f763a96f.png)

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/33410765-bd5752f4-d5bc-11e7-80af-5f09550cf1be.png)

**Comment by Gericop** [comment]
You cannot unfortunately and it is not planned to be implemented.

**Comment by TCQQ** [comment]
Show you an example

First picture the app theme：
                    primary color = "color.purple"
                    accent color = "color.white"
                     
![image](https://user-images.githubusercontent.com/10644057/33470548-d055fa80-d6a3-11e7-89fa-c4149639cb9c.png)

Second picture the app theme:
                    primary color = "color.white"
                    accent color = "color.pink"
![image](https://user-images.githubusercontent.com/10644057/33470570-e77a35e6-d6a3-11e7-95e3-4b59e5d08db4.png)

**Comment by TCQQ** [comment]
So how to deal with this situation?

**Comment by TCQQ** [comment]
If add a setDateTimePickerPrimaryColor method in the code, you can solve this problem

**Comment by Gericop** [comment]
The header of the date time picker uses the accent color from the theme using `android:background="?colorAccent"` (you can see it [here](https://github.com/Gericop/DateTimePicker/blob/master/datetimepicker/src/main/res/layout/date_picker_header_material.xml)). If it appears to be white, you didn't set the accent color properly in your theme.

**Comment by TCQQ** [comment]
I setted, read it: 


Theme：
                    primary color = "color.purple"
                    accent color = "color.white"

![image](https://user-images.githubusercontent.com/10644057/33470548-d055fa80-d6a3-11e7-89fa-c4149639cb9c.png)

Theme：
                    primary color = "color.white"
                    accent color = "color.pink"

![image](https://user-images.githubusercontent.com/10644057/33470570-e77a35e6-d6a3-11e7-95e3-4b59e5d08db4.png)

**Comment by TCQQ** [comment]
colorAccent may be white, it may be color

**Comment by TCQQ** [comment]
So the date time picker needs support for programmatically changing colors, the problem can be solved

**Comment by TCQQ** [comment]
Hopefully, can add a way to programmatically change the "date time picker" color, therefore, the above problems can be solved, thank you

**Comment by Gericop** [comment]
The date time picker is simply the port of the official one and as such, I do not really intend to add such functionality.

Why do you set the accent color to white? Widgets, like Checkboxes wouldn't be visible either.

**Comment by TCQQ** [comment]
"Why do you set the accent color to white?"
-Because the application allows the user to change the "primary color" and "accent color" to any color, So I have to programmatically be compatible with this problem

"Widgets, like Checkboxes wouldn't be visible either."
-No, widgets, like Checkboxes ... can change the colors programmatically
