### ISSUE TITLE
Feedback ColorPicker BUG

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#126]
com.takisoft.fix:preference-v7:27.0.2.0
com.takisoft.fix:preference-v7-extras:27.0.2.0
![image](https://user-images.githubusercontent.com/10644057/33522245-cfeebe1c-d822-11e7-9cb5-66bb85eb8b81.png)

com.takisoft.fix:preference-v7:27.0.1.0
com.takisoft.fix:preference-v7-extras:27.0.1.0
![image](https://user-images.githubusercontent.com/10644057/33522269-9e8153ac-d823-11e7-9e0a-2ddc28c047b1.png)

        <ColorPickerPreference
            app:pref_columns="5"
            android:persistent="true"
            android:key="cp_color_picker"
            android:title="Select a color:" />

**Comment by Gericop** [comment]
This is a bug in [Gericop/ColorPicker](/Gericop/ColorPicker). It'll be fixed soon.

**Comment by TCQQ** [comment]
Ok.

**Comment by TCQQ** [comment]
Hi, what time can fix? i want use 27.0.2.0

**Comment by TCQQ** [comment]
com.takisoft.fix:preference-v7-extras:27.0.2.0
![image](https://user-images.githubusercontent.com/10644057/34632788-852b90bc-f2b2-11e7-9e7e-dce0c8b072a8.png)

but new color picker library version is 1.0.3

![image](https://user-images.githubusercontent.com/10644057/34632807-9e65ff2c-f2b2-11e7-8e56-0d780972ecff.png)
