### ISSUE TITLE
Feedback preference-v7 problem

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#129]
Hi, how to programmatically change preference icon color? This is useful for customizable themes apps, because night theme mode and day theme mode the icon color are different.

![image](https://user-images.githubusercontent.com/10644057/33796003-2fc57a48-dd27-11e7-8994-37183a6e2b19.png)
![image](https://user-images.githubusercontent.com/10644057/33796005-31f2baba-dd27-11e7-95b1-792487e1408b.png)

**Comment by Gericop** [comment]
I think this has been discussed in #99. This has nothing to do with preferences and you should implement it your way.

**Comment by TCQQ** [comment]
But I would like to change the color function can be further encapsulated in the "preferences", so the structure will be more clear

ex:
            ImageView imageView = (ImageView) view;
            Drawable wrappedDrawable = DrawableCompat.wrap(imageView.getDrawable());
            DrawableCompat.setTint(wrappedDrawable, colorId);
            imageView.setImageDrawable(wrappedDrawable);
            imageView.invalidate();

**Comment by tcqq** [comment]
I found a better solution that only needs to be configured in style, and create `values-night`->`color`

```
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <item name="preferenceTheme">@style/PreferenceTheme</item>
    </style>

    <style name="PreferenceTheme" parent="@style/PreferenceThemeOverlay.v14.Material">
        <item name="android:tint">@color/pref_icon_color</item>
    </style>
```

and add 

```
    override fun onCreate(savedInstanceState: Bundle?) {
        delegate.setLocalNightMode(if (ThemeOverlayManager.isDarkTheme()) AppCompatDelegate.MODE_NIGHT_YES else AppCompatDelegate.MODE_NIGHT_NO)
        super.onCreate(savedInstanceState);
}
```

**Comment by ankitbatra11** [comment]
Above solution does not work for me.

**Comment by tcqq** [comment]
@ankitbatra11 I updated the code, please check.
