### ISSUE TITLE
Feedback ColorPickerPreference problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#131]
If add PreferenceScreen outside of ColorPickerPreference, the color order will change
![image](https://user-images.githubusercontent.com/10644057/33801419-c7fa856a-dd95-11e7-9647-fa2b963cfdb2.png)
![image](https://user-images.githubusercontent.com/10644057/33801430-e6ea1b20-dd95-11e7-92e2-1b7cfbb1c302.png)

**Comment by Gericop** [comment]
I think you use two different set of colors. For example, the color visible in the second image's 3rd row in the 1st column is nowhere to be found in the first image.

**Comment by TCQQ** [comment]
Is the same data, I only added PreferenceScreen outside of ColorPickerPreference, then color order will change.

    <PreferenceScreen
        android:key="preference_screen_palette"
        android:title="@string/preference_fragment_settings_theme_palette">

        
        <ColorPickerPreference
            android:key="color_picker_preference_primary_color"
            android:persistent="true"
            android:title="@string/preference_fragment_settings_theme_primary_color"
            app:pref_columns="5" />

    </PreferenceScreen>

**Comment by Gericop** [comment]
I don't understand what you mean by "added PreferenceScreen outside of ColorPickerPreference". Post your whole XML.

**Comment by TCQQ** [comment]
【
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">
  
    <PreferenceScreen
        android:key="preference_screen_palette"
        android:title="@string/preference_fragment_settings_theme_palette">

        
        <ColorPickerPreference
            android:key="color_picker_preference_primary_color"
            android:persistent="true"
            android:title="@string/preference_fragment_settings_theme_primary_color"
            app:pref_columns="5" />

    </PreferenceScreen>
</PreferenceScreen>
】

**Comment by Gericop** [comment]
Provide a sample repo where I can test it. This doesn't happen in any of my tests.

**Comment by TCQQ** [comment]
[main.zip](https://github.com/Gericop/Android-Support-Preference-V7-Fix/files/1562623/main.zip)
