### ISSUE TITLE
Feedback ListPreference problem

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#133]
Hi, hope "ListPreference" can support the settings radio button and cancel button text color.

![image](https://user-images.githubusercontent.com/10644057/33852310-f7d98b5e-def4-11e7-8dab-ad6e03133f9f.png)
![image](https://user-images.githubusercontent.com/10644057/33853848-70564d7e-defa-11e7-9eef-ea1a63f45e11.png)
![image](https://user-images.githubusercontent.com/10644057/33852339-15644524-def5-11e7-8320-bfa9daa42be7.png)

As can be seen from the picture, because the "PreferenceCategory" supports setting the text color, so to avoid the white background color and white text color together match the problem.

**Comment by Gericop** [comment]
It's not possible to change either the color of the radio button nor the text color of the cancel button because this is an `AlertDialog` which provides no methods for changing colors dynamically.
