### ISSUE TITLE
Feedback preference problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#134]
Hello, i would like to programmatically change the TextView of id = "tv_text" in "preference_custom" to "Hello World" and how should I change it?

TestPreferenceFragment.java:

public class TestPreferenceFragment extends PreferenceFragmentCompatDividers {

    @Override
    public void onCreatePreferencesFix(@Nullable Bundle savedInstanceState, String rootKey) {
        addPreferencesFromResource(R.xml.preference_test);
    }

preference_test.xml:

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

    <Preference
        android:key="preference_custom"
        android:layout="@layout/preference_custom" />
</PreferenceScreen>

preference_custom.xml:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/tv_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:padding="16dp"
        android:text="Text"/>
</RelativeLayout>

**Comment by TCQQ** [comment]
If I inherit the "PreferenceFragment" from the "TestPreferenceFragment" and customize the "CustomPreference" at the same time, I will customize the layout display and at the same time the id = "tv_text" the text will be change.

preference_test.xml:

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

    <com.changrui.tt.test.VolumeSettingPreference />

</PreferenceScreen>

TestPreferenceFragment.java:

public class TestPreferenceFragment extends PreferenceFragment {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.preference_test);
    }
}

CustomPreference.java:

public class CustomPreference extends Preference {

    TextView mTextView;

    public CustomPreference (Context context) {
        super(context);
    }

    @Override
    protected View onCreateView(ViewGroup parent) {
        super.onCreateView(parent);
        View content = LayoutInflater.from(getContext()).inflate(R.layout.preference_custom, null);
        return content;
    }

    @Override
    protected void onBindView(View view) {
        super.onBindView(view);
        mTextView = view.findViewById(R.id.tv_text);

        mTextView.setText("Hello World");
    }
}

![image](https://user-images.githubusercontent.com/10644057/33953738-029d6574-e071-11e7-914a-f7df5d4e7976.png)

But if I inherit "TestPreferenceFragment" as "PreferenceFragmentCompatDividers", the layout will not be displayed and the text will not be changed.

TestPreferenceFragment.java:

public class TestPreferenceFragment extends PreferenceFragmentCompatDividers  {

    @Override
    public void onCreatePreferencesFix(@Nullable Bundle savedInstanceState, String rootKey) {
        addPreferencesFromResource(R.xml.preference_test);
    }
}

**Comment by TCQQ** [comment]
How can I use a custom layout and change the text in a custom layout while inheriting "PreferenceFragmentCompatDividers"?

**Comment by Gericop** [comment]
Check the logcat for any exceptions being thrown. Also, is it `CustomPreference` or `VolumeSettingPreference` now? Could you create a new repo with a test project? Because these code pieces don't make too much sense.

**Comment by TCQQ** [comment]
[main.zip](https://github.com/Gericop/Android-Support-Preference-V7-Fix/files/1560287/main.zip)
