### ISSUE TITLE
Use RingtonePreference

### ISSUE THREAD

**Issue by mikalofy** [Gericop/Android-Support-Preference-V7-Fix#136]
Hi Gericop,

I want an example of RingtonePreference with control in PreferenceFragment

**Comment by Gericop** [comment]
What do you mean? The [wiki](https://github.com/Gericop/Android-Support-Preference-V7-Fix/wiki/Preference-types#ringtonepreference) has all the information you need.

**Comment by mikalofy** [comment]
Thanks for your answer, but I've followed this wiki and it crached when I clicked in the ringtonepreference! Bellow is the code:
 
![xml](https://user-images.githubusercontent.com/34678154/34195983-110252dc-e571-11e7-9f9b-4ac21a423725.PNG)


And the following code of my preferenceFragment

![java1](https://user-images.githubusercontent.com/34678154/34196142-cee3c7ae-e571-11e7-8965-f6a921789a4b.PNG)

What line I'm wrong?

**Comment by Gericop** [comment]
What does the `dialogRingtone()` call do? 

Also, you don't need to use the fully qualified name of the preference in the XML. So, instead of
```
<com.takisoft.fix.support.v7.preference.RingtonePreference [...] />
```
you can use
```
<RingtonePreference [...] />
```

**Comment by mikalofy** [comment]
OK, I'll try this and I'll return back on you

**Comment by mikalofy** [comment]
When I used only <Rington,ePreference[...] /> I got this error:
![error1](https://user-images.githubusercontent.com/34678154/34205955-8a18e13a-e595-11e7-914f-88b1bfc4429f.PNG)

**Comment by Gericop** [comment]
Try a clean build. Also, are you sure everything is there as expected? It seems like you're not using this library. Try the sample app and see if it works.

**Comment by mikalofy** [comment]
Yes, I used your library, this is the content of my app gradle 

compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:palette-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.android.support:support-compat:27.0.2'
    compile 'com.android.support:support-v13:27.0.2'
    compile 'com.takisoft.fix:preference-v7:27.0.2.0'
    //compile 'com.takisoft.fix:preference-v7-extras:27.0.2.0'
    compile 'com.takisoft.fix:preference-v7-ringtone:27.0.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

**Comment by Gericop** [comment]
Did you try the sample app?

**Comment by mikalofy** [comment]
I'll try now and return back to you after

**Comment by mikalofy** [comment]
I'll try now and return back to you after

**Comment by mikalofy** [comment]
It worked with the sample app! But in my app, I'm using <preferences-headers [...]><header[...]/><header[...]/></preferences-headers>!

So how can I open the fragment for RingtonePreference from header! May be that the reason of my crach

**Comment by Gericop** [comment]
I'm not sure the support preferences lib actually support preference headers.

**Comment by mikalofy** [comment]
Ah, may be you will go add it in the future! Anyway thank you very much for all your helps! I apreciate!
