### ISSUE TITLE
PreferenceManager.setDefaultValues() with AutoSummaryEditTextPreference

### ISSUE THREAD

**Issue by adrcotfas** [Gericop/Android-Support-Preference-V7-Fix#137]
I'm getting this error when trying to set the default values in the PreferenceManager:
` android.view.InflateException: Binary XML file line #0: Error inflating class (not found)AutoSummaryEditTextPreference`
This is also valid for RingtonePreference:
`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.preference.RingtonePreference" `
What can I do about it?
Thanks!

**Comment by Gericop** [comment]
You're probably not using the correct fragment. Could you post your code and XML?

**Comment by adrcotfas** [comment]
The code was copy pasted from the demo app. In the meantime I realized that I don't need a PreferenceManager, so you could close this if you want.
Thanks for the prompt response!

**Comment by piszoka** [comment]
This change should also solves this:
https://github.com/Gericop/Android-Support-Preference-V7-Fix/pull/166
