### ISSUE TITLE
Uptate preference-v7-extras

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#138]
In “com.takisoft.fix:preference-v7-extras:27.0.2.0” the ColorPicker version is “1.0.2”, but new version is “1.0.3”, now the “1.0.2” have problem, “1.0.3” already fixed, please update in preference-v7-extras the ColorPicker version, thanks.

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/34936183-5b10d04c-fa1b-11e7-9b2b-4b96a6afab0c.png)
![image](https://user-images.githubusercontent.com/10644057/34936197-6f4af448-fa1b-11e7-98a0-decdfa2eb557.png)

**Comment by Gericop** [comment]
Updated to v1.0.4 in **v27.1.0.0**
