### ISSUE TITLE
The splitter fix doesn't work with animation

### ISSUE THREAD

**Issue by Mygod** [Gericop/Android-Support-Preference-V7-Fix#14]
When an item's height changed (for example when I removed the summary of a preference), the splitter bumps instantly to the final location while the rest of the content moves there. The inconsistency looks uncomfortable.

**Comment by Gericop** [comment]
The latest version (23.2.0) of the support library introduces the dividers so I'm removing the custom implementation. You should test this behavior with the new version and if the bug still exists, file a bug report to the Android devs.

**Comment by Mygod** [comment]
Okthx.
