### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by MatFl** [Gericop/Android-Support-Preference-V7-Fix#140]
I would like to propose a change of the license of this library, because the Unlicense brings a few problems:
https://en.wikipedia.org/wiki/Unlicense#Reception

For example it is not compatible with some country's legal systems.

A better license would probably be Creative Commons Zero (CC0), because is has fallback for the legal  issues in some countries. https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_/_public_domain

**Comment by RocketRider** [comment]
Would love to see this changes as well. As a German developer I see the issue here.
https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense/147120#147120

**Comment by Gericop** [comment]
Never thought Unlicense (public domain) would be an issue. I'll look into the CC0 one, it seems okay.

**Comment by MatFl** [comment]
Is there any progress on this? I would prefer to be on the safe side of the legal stuff.

**Comment by Gericop** [comment]
Yes, the next major version (28 / X) will be relicensed.

**Comment by Gericop** [comment]
The AndroidX version is relicensed to Apache v2. You can start using it now, check out https://bintray.com/takisoft/android for the available artifacts.

**Comment by RocketRider** [comment]
Thank you :+1:
