### ISSUE TITLE
Feedback Colorpicker not work.

### ISSUE THREAD

**Issue by LeeReindeer** [Gericop/Android-Support-Preference-V7-Fix#144]
When i add `ColorPickerPreference` in `preference.xml`, Android studio comes a warning: `Element ColorPickerPreference is not allowed here less... (Ctrl+F1) 
This inspection highlights unallowed XML tags in Android resource files and AndroidManifest.xml`

 After running my app, the settingFragment show a blank page.

This is my prefenence.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
 <!--other setting-->  
  <PreferenceCategory
        android:title="Colors">

        <ColorPickerPreference
            android:defaultValue="#88C440"
            android:dialogTitle="Color"
            android:key="pre_key_color1"
            android:persistent="false"
            android:title="ColorPickerPreference" />
    </PreferenceCategory>

</PreferenceScreen>
```
This is my build.gradle:
```gradle
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.takisoft.fix:preference-v7:27.1.0.0'
    implementation 'com.takisoft.fix:preference-v7-colorpicker:27.1.0.0'
```

Please help, thanks.

**Comment by Gericop** [comment]
Just ignore the warning. That is shown because the `ColorPickerPreference` is not a standard preference tag.

You probably don't import the appropriate fragment base class for your fragment. Show your java / kotlin code here, too.

**Comment by LeeReindeer** [comment]
@Gericop 
Here is my code, I import the appropriate fragment..
```java
import com.takisoft.fix.support.v7.preference.EditTextPreference;
import com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat;

public class SettingFragment extends PreferenceFragmentCompatr{
    @Override
    public void onCreatePreferencesFix(@Nullable Bundle savedInstanceState, String rootKey) {
        setPreferencesFromResource(R.xml.preference, rootKey);
    }
}
```
And i also can find

**Comment by Gericop** [comment]
Check the logcat for warnings / errors, it might show something. Does the sample app work on your device?

**Comment by LeeReindeer** [comment]
@Gericop 
The sample works well.And after I reimport dependencies and clean and rebuild, it works...sorry for this.

**Comment by Gericop** [comment]
No problem, gradle / Android Studio can do interesting things sometimes.
