### ISSUE TITLE
Support Library 27.1.1 released

### ISSUE THREAD

**Issue by RocketRider** [Gericop/Android-Support-Preference-V7-Fix#148]
https://developer.android.com/topic/libraries/support-library/revisions.html#27-1-1

**Comment by FranckRJ** [comment]
Is it safe to manually include the latest support preference lib without waiting for this lib to be updated ?

Like this (in the build.gradle) :

    implementation 'com.android.support:preference-v7:27.1.1'
    implementation 'com.android.support:preference-v14:27.1.1'

**Comment by Mygod** [comment]
Looks good to me.

**Comment by FranckRJ** [comment]
Ok, thanks.

**Comment by Gericop** [comment]
Released v**27.1.1.0**.
