### ISSUE TITLE
RadioButton in listpreference is black

### ISSUE THREAD

**Issue by saquer0716** [Gericop/Android-Support-Preference-V7-Fix#15]
In pre-lollipop device, listpreference's popped dialog comes with black radio button. Do we need a ListPreferenceDialogFragmentCompatFix class?

**Comment by Gericop** [comment]
I'll try to look into this matter, I'd rather find a style-using solution than implement a new class for this too...

**Comment by Gericop** [comment]
The latest version (23.2.0) of the support library has finally fixed this issue.
