### ISSUE TITLE
ColorPickerPreference large size layout error

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#150]
@Gericop 

```
        <com.takisoft.fix.support.v7.preference.ColorPickerPreference
            android:defaultValue="?attr/colorPrimary"
            android:key="color_picker_pref_primary_color"
            android:persistent="true"
            android:title="@string/theme_settings_primary_color"
            app:pref_columns="5"
            app:pref_size="large" />
```

![image](https://user-images.githubusercontent.com/10644057/39071735-c7b0930a-451a-11e8-83c6-8a9c4713a849.png)
![image](https://user-images.githubusercontent.com/10644057/39071749-d0d4a520-451a-11e8-9cf0-efe4c2437dfb.png)

**Comment by Gericop** [comment]
The `pref_columns` attribute enforces the given number of columns to be present. One way of fixing it is to not set the value or set different values for different screen sizes.
