### ISSUE TITLE
Fix example can't preview problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#154]
@Gericop The code for the example now cannot display the preview, If you use `ColorPickerPreference` preview will not be displayed, if you use `com.takisoft.fix.support.v7.preference.ColorPickerPreference` preview will be displayed.

![image](https://user-images.githubusercontent.com/10644057/39417968-2cf4ff46-4c8a-11e8-9250-d424d0e55983.png)
![image](https://user-images.githubusercontent.com/10644057/39417996-5b190962-4c8a-11e8-9ef4-81b6d148ae40.png)

**Comment by Gericop** [comment]
This is an "intended" behavior. The Android Studio only recognizes the built-in types without the fully qualified name and this cannot be "fixed" externally.
