### ISSUE TITLE
Need updated version for 28.0.0

### ISSUE THREAD

**Issue by Hodkinson** [Gericop/Android-Support-Preference-V7-Fix#161]

**Comment by Mygod** [comment]
I believe you can use 27.1.1.1 with preference 28.0.0-alpha3. Just replace `PreferenceFragmentCompatDividers` with `PreferenceFragmentCompat` and use #111 for dividers for custom preferences like `SimpleMenuPreference`.

**Comment by Hodkinson** [comment]
Thank you, will try it.
