### ISSUE TITLE
TimePickerPreference style error

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#162]
@Gericop TimePickerPreference button style error.

![image](https://user-images.githubusercontent.com/10644057/41508056-cd3359d8-7270-11e8-88d5-bbdafa44a456.png)

Style:
-
```
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorSecondary">@color/colorSecondary</item>
    </style>
```

**Comment by tcqq** [comment]
@Gericop Use `AppCompatButton` Instead of `Button` will fixed Timepicker Button Style Problems. But Datapicker also has this problem, please check.

**Comment by Gericop** [comment]
This will be fixed by the date picker lib v1.0.7-alpha3 (actually alpha1 fixes it but this problem is non-existent in the support lib v28.0.0-alpha1).

**Comment by tcqq** [comment]
Thanks for fixing, Sync “preference-v7-extras” please.

**Comment by Gericop** [comment]
v**28.0.0.0-alpha3** is not released yet.

**Comment by tcqq** [comment]
@Gericop "preference-v7-extras" version updated to "v28.0.0.0-alpha3" will sync date picker lib v1.0.7-alpha3？

**Comment by Gericop** [comment]
Yes.
