### ISSUE TITLE
Get hours and minutes under listener for TimePickerPreference

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#163]
@Gericop I added setOnPreferenceChangeListener for TimePickerPreference, How should I get hours and minutes under listener? Thanks.

```
timePickerPreference.setOnPreferenceChangeListener { preference, newValue ->
}
```

**Comment by Gericop** [comment]
The `newValue` contains the time string formatted as `HH:mm` (as seen in the [wiki](https://github.com/Gericop/Android-Support-Preference-V7-Fix/wiki/Preference-types#timepickerpreference)). However, the preference has also methods for getting the hour and the minute values separately using the `getHourOfDay()` and `getMinute()` methods, respectively.

**Comment by tcqq** [comment]
`getHourOfDay()` and `getMinute()` get thepreviously set value, I want to get the value currently being set, how should I use "newValue" to get "HourOfDay" and "Minute" values?

**Comment by tcqq** [comment]
OK, thanks, I got it in this way.

```
newValue as TimePickerPreference.TimeWrapper
newValue.hour
```
