### ISSUE TITLE
Update to Support Library 23.3.0

### ISSUE THREAD

**Issue by Mygod** [Gericop/Android-Support-Preference-V7-Fix#17]

**Comment by Mygod** [comment]
According to [this page](http://developer.android.com/intl/zh-cn/tools/support-library/index.html):

>Changes for v7 Preference library:
>* Fixed issue where PreferenceFragmentCompat would crash if dividerHeight is specified. (Issue 204778)

**Comment by Gericop** [comment]
I would update, but my SDK Manager says that the latest version is 23.2.1...

**Comment by Mygod** [comment]
Mmm refresh maybe?

**Comment by Gericop** [comment]
No luck, I even downloaded a new SDK manager and it still lists 23.2.1 as the latest... WTF is going on here?!

**Comment by Mygod** [comment]
Wait my Android SDK Manager displays 23.2.1 now. Maybe they unpublished it?

**Comment by Gericop** [comment]
That would be a new low I guess.

**Comment by yccheok** [comment]
@Gericop Thanks for taking the effort of maintaining the fix for preference workaround. I came back here to this repository again, after figuring several things were broken, after upgrading to latest support library.

**Comment by eku** [comment]
23.3. is available for some days.

**Comment by Gericop** [comment]
I know now, I'll update the things by Friday (I'm a bit busy now, university stuff, you know...)

**Comment by Gericop** [comment]
Upgraded to v23.3.0. No real changes in the official API though...
