### ISSUE TITLE
Fix SeekBar layout problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#175]
@Gericop After changing the SeekBar value. The right side of the SeekBar value shows the scroll bars that should not be displayed.

![image](https://user-images.githubusercontent.com/10644057/43029965-bd045348-8cbd-11e8-9c82-337aff641f59.png)

**Comment by Gericop** [comment]
Will be fixed in v28.0.0.0

**Comment by gregkorossy** [comment]
Released v**28.0.0.0**
