### ISSUE TITLE
Could not find com.takisoft.fix:preference-v7-material:28.0.0.0-alpha3

### ISSUE THREAD

**Issue by marbat87** [Gericop/Android-Support-Preference-V7-Fix#176]
Hi,

I get the following error while trying to add the preference-v7-material library to my dependencies:
`Could not find com.takisoft.fix:preference-v7-material:28.0.0.0-alpha3`

I have these repositories configured.. do I miss anything?
```
repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        google()
    }
```

Thanks in advance

**Comment by Ninjalan** [comment]
Having the same issue here. "Could not find com.takisoft.fix:preference-v7-material:28.0.0.0-alpha3"

**Comment by Gericop** [comment]
Sorry, forgot to add the package to jcenter. Just submitted the request, until that you can use the artifact by adding the maven repo directly:

```gradle
repositories {
    maven {
        url "https://dl.bintray.com/gericop/maven"
    }
}
```

**Comment by Ninjalan** [comment]
That did the trick. Thanks!

**Comment by Gericop** [comment]
It's now available on jcenter.
