### ISSUE TITLE
Can we provide a more flexible way, for user to turn on and turn off dividers, for category section and non-category section?

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#18]
In recent commit, I saw custom divider drawing feature is being removed

https://github.com/Gericop/Android-Support-Preference-V7-Fix/commit/a32b444a157fabd5836a59ff532f450330737a86

However, I would like to have a feature, where I can have divider on category section, and no divider on non-category section. As a result, I adopt your old code from https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/9f3595d054f070b1b0b41255c019414f308d02d2/app/src/main/java/android/support/v7/preference/PreferenceFragmentCompatFix.java

I modify the custom divider drawing code, to make sure it only draw on category section - https://gist.github.com/yccheok/9da06876cbde1cb0849182647e030743

It looks something like http://i.imgur.com/pq3piNC.png

Although I able to achieve my own custom divider drawing on category section only, and turn off divider for non-category section. I believe other users might be interested too.

It might good to have such feature in official release of PreferenceFragmentCompatFix.java

Thank you for providing an amazing fix to this problem.

**Comment by Gericop** [comment]
Sure, I'll include it in the next release, probably by Friday.

**Comment by Gericop** [comment]
So, I implemented a complex solution which is easy to use. It's not on the master branch, so be sure to check out the [feature/dividers](https://github.com/Gericop/Android-Support-Preference-V7-Fix/tree/feature/dividers) one. You'll find new class called [`PreferenceFragmentCompatDividers`](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/feature/dividers/app/src/main/java/android/support/v7/preference/PreferenceFragmentCompatDividers.java) there extending the original fix with customizable dividers. Also, [`MyPreferenceFragment`](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/feature/dividers/app/src/main/java/com/takisoft/preferencefix/MyPreferenceFragment.java), that is used for testing, implements this new class now. Please, check its behavior and if it fits the needs and is reliable, I'll publish it to the master branch.

**Comment by Gericop** [comment]
Added this feature to `PreferenceFragmentCompatDividers`, call `setDividerPreferences(...)` with the appropriate flags to use it.
