### ISSUE TITLE
Upgrade from v7:27.1.1.1 to v7:28.0.0.0 caused unwanted left margin

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#184]
Hi, I just upgraded from v7:27.1.1.1 to v7:28.0.0.0 

    implementation 'com.takisoft.fix:preference-v7:28.0.0.0'

However, I'm getting unwanted left margin

![a](https://user-images.githubusercontent.com/308276/46345496-57b9c380-c677-11e8-9ee2-906b235843ec.png)

I'm using `com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat` and `@style/PreferenceFixTheme.Light.NoActionBar`. Any idea for such behavior? Thank you very much!

**Comment by gregkorossy** [comment]
This is the intended behavior of the new material design for preferences. Both #132 and #183 are about this.

**Comment by Mygod** [comment]
I think there is a way to easily change the global default `iconSpaceReserved` but I might be wrong.

**Comment by zhanghai** [comment]
> I think there is a way to easily change the global default `iconSpaceReserved` but I might be wrong.

Yes there is, by creating `res/values-sw360dp-v13/values-preference.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:tools="http://schemas.android.com/tools">
    <bool name="config_materialPreferenceIconSpaceReserved" tools:ignore="MissingDefaultResource,PrivateResource">false</bool>
    <dimen name="preference_category_padding_start" tools:ignore="MissingDefaultResource,PrivateResource">0dp</dimen>
</resources>
```

This fixes both the preference and the category. I've also [posted this on StackOverflow](https://stackoverflow.com/a/52960668).
