### ISSUE TITLE
EditTextPreference and design support library

### ISSUE THREAD

**Issue by SQ5TB** [Gericop/Android-Support-Preference-V7-Fix#19]
EditTextPreference is displayed incorrectly after adding support library com.android.support:design:23.3.0 into project.
There is only top title header part with no edit entry and bottom buttons.

![edittextpreferencefix_title](https://cloud.githubusercontent.com/assets/7237381/15189666/3cdcc46c-17ac-11e6-86f0-b2368d05cc09.png)

this screenshot is taken from Android 6.0
Older versions have next error during start process 
android.content.res.Resources$NotFoundException: File res/drawable/abc_list_selector_holo_light.xml from color state list resource ID #0x7f020032

**Comment by Gericop** [comment]
Is this a real device or an emulator?
Also, did you try using my fix library?
- add `compile 'com.takisoft.fix:preference-v7:23.3.0.4-beta'` instead of the original one
- define `<color name="preference_accent">@color/accent</color>` where @color/accent is your accent color
- use one of `@style/PreferenceFixTheme`, `@style/PreferenceFixTheme.Light`, `@style/PreferenceFixTheme.DayNight` (or the `NoActionBar` extension with one of these) as your base theme

**Comment by Gericop** [comment]
@SQ5TB By the way, make sure you extend [`AppCompatActivity`](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html), not the normal `Activity`.

**Comment by SQ5TB** [comment]
This example is taken from your example application. I only modified compile dependencies in gradle file. Previously have the same error on my application. This environment is Genymotion emulator. I don't have real Android 6 phone. If design support lib is commented out in dependencies then this demo app works fine on my phone (4.2.2).

**Comment by SQ5TB** [comment]
my dependencies in gradle file

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.takisoft.fix:preference-v7:23.3.0.4-beta'
    compile 'com.android.support:design:23.3.0'
}
My activity extends AppCompatActivity.

**Comment by Gericop** [comment]
I look into it now. Meanwhile, just to make it clear, you checked out the project and only added the design support lib?

**Comment by SQ5TB** [comment]
Yes. Code is from your github (version 23.3.0.4-beta).

**Comment by Gericop** [comment]
I see, it seems like that for whatever reasons, it makes the EditText use the v7 PreferenceOverlay instead of the material one... Interesting...

**Comment by Gericop** [comment]
Okay, I see the problem, the support preference lib's R file's `editTextPreferenceStyle` is being overriden.

**Comment by Gericop** [comment]
Fixed, I'll publish the new (23.4.0.1) version soon.

**Comment by Gericop** [comment]
Fixed and the new library is online! You should have no problem now.
Just use `compile 'com.takisoft.fix:preference-v7:23.4.0.1'`.
