### ISSUE TITLE
androidx.preference 1.1.0-alpha02

### ISSUE THREAD

**Issue by Mygod** [Gericop/Android-Support-Preference-V7-Fix#190]
> **New features**
> * You can now set a SummaryProvider on a Preference to dynamically configure its summary whenever the Preference is updated, or becomes visible to the user.
> * Added default SummaryProvider implementations for ListPreference and EditTextPreference, which when set will automatically update the summary of the Preference to reflect its saved value, or ‘Not Set’ if no value has been saved. These can be set with app:useSimpleSummaryProvider=”true”
>
> ...
> **Bug fixes**
> * Fixed iconSpaceReserved not working correctly with PreferenceCategories.
> * Fixed PreferenceCategories not using colorAccent for their title’s color below API 21.
> * Fixed some SeekBarPreference layout inconsistencies below API 21.

**Comment by zhanghai** [comment]
Why the string "Not Set"? How to localize it? What if one think "None" is better?

All in all, please don't add functionality to basic preferences, they should only contain fixes; extend them with `AutoSummaryEditTextPreference` etc is much better.

**Comment by Mygod** [comment]
@DreaminginCodeZH These are changes from Google's side. I'm only [quoting them](https://developer.android.com/jetpack/androidx/androidx-rn). Maybe you should do something about that. :man_shrugging: :stuck_out_tongue:

**Comment by zhanghai** [comment]
Wow didn't expect Google doing this, my apologies. I've nothing to say now. Sorry for the disturbance 😅

**Comment by gregkorossy** [comment]
Sorry for the delay, I was abroad.
The "Not set" text has translations, so it shouldn't be a problem, and the `SummaryProvider` is not enabled by default. Maybe it will be useful someday though 😅

**Comment by Mygod** [comment]
1.1.0-alpha02 is updated with even more new features.

**Comment by gregkorossy** [comment]
1.1.0-alpha04 of the lib is coming soon...

**Comment by gregkorossy** [comment]
1.1.0-alpha04 is out. The README is to-be-updated.

**Comment by gregkorossy** [comment]
Also, 1.1.0-alpha05 is out as a quick fix for appcompat 1.1.0-alpha05 (contains fragment 1.1.0-alpha08 which is the actual cause) being incompatible with preferences 1.1.0-alpha01 through 1.1.0-alpha04.
