### ISSUE TITLE
PreferenceScreen deprecated in Android Q

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#196]
@Gericop PreferenceScreen deprecated in Android Q

![image](https://user-images.githubusercontent.com/10644057/54873033-03fb8c00-4e09-11e9-92bb-d38a2c4cbac8.png)

**Comment by tcqq** [comment]
I found solution and only need to modify it to: `androidx.preference.PreferenceScreen`

**Comment by 9306488494** [comment]
You also need to change in the manifest

      <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
