### ISSUE TITLE
Request to update the version of the preference library

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#197]
@Gericop  1.1.0-alpha04 is the latest version of the preference library.

**Comment by gregkorossy** [comment]
Work in progress now.

**Comment by gregkorossy** [comment]
A little teaser...

![separated_switch](https://user-images.githubusercontent.com/5181621/56006260-7d81ee00-5cd4-11e9-8337-c5de33a3f6bf.png)

**Comment by gregkorossy** [comment]
Some more teaser...
![Screenshot_1555335893](https://user-images.githubusercontent.com/5181621/56137739-c1efe100-5f95-11e9-87c4-03678e281006.png) ![Screenshot_1555335896](https://user-images.githubusercontent.com/5181621/56137749-c4ead180-5f95-11e9-8917-d770a8186703.png)

**Comment by gregkorossy** [comment]
1.1.0-alpha04 is out. The README is to-be-updated.

**Comment by gregkorossy** [comment]
Also, 1.1.0-alpha05 is out as a quick fix for appcompat 1.1.0-alpha05 (contains fragment 1.1.0-alpha08 which is the actual cause) being incompatible with preferences 1.1.0-alpha01 through 1.1.0-alpha04.
