### ISSUE TITLE
keyboard do not hide when cancel button is clicked of editTextPreference

### ISSUE THREAD

**Issue by brunowagner** [Gericop/Android-Support-Preference-V7-Fix#199]
I am using inputType = "number" in my edit text preference, and if I click in cancel button of edit text preference, the keyboard with inputType = "number" hide (or disappear) end a general keyboard (inputType = "text" for exemple) still stay visible. Maybe in this moment inputType = "number" becomes in "text".

**Comment by gregkorossy** [comment]
What version of the lib do you use? What's the OS version? What device? Could you reproduce this with the sample app?

**Comment by brunowagner** [comment]
I discovered what was wrong!
In Manifest, I was using android:windowSoftInputMode="stateHidden" for my SettingsActivity.
When I removed this line, the problem disappeared.

If I change "stateHidden" to "stateAlwaysHidden", it also resolves.
