### ISSUE TITLE
Cannot seem to change the divider Drawable (Just want to change color)

### ISSUE THREAD

**Issue by bignadad** [Gericop/Android-Support-Preference-V7-Fix#20]
I have a fragment extending PreferenceFragmentCompatDividers

in the onCreatePreferencesFix method

I am using this

setDivider(ResourcesCompat.getDrawable(getResources(), R.drawable.pref_divider, null));
 but the divider does not change.

I have also tried setting the divider preferences and height with no luck.

I have even tried getting the drawable with the old getResources.getdrawable method. I know that wouldn't matter just wanted to put it out there.

How can i change the color of the divider?

**Comment by Gericop** [comment]
@bignadad What version of Android are you using? Is it a real device or an emulator?

**Comment by bignadad** [comment]
6.0.1 galaxy s7

**Comment by bignadad** [comment]
real device

**Comment by Gericop** [comment]
Well, I see the problem. I'll try to come up with something, but in the meanwhile, try calling these methods in `onCreateView(...)` (*after the `super` call!*). Make sure you call `setDividerPreferences(...)` before `setDivider(...)` or `setDividerHeight(...)` (*you don't have to call `setDividerPreferences(...)` unless you want to customize the position of the dividers*).

**Comment by bignadad** [comment]
That worked! Thanks

**Comment by Gericop** [comment]
Changed the way of call so that `setDividerPreferences(...)` (and the other two methods) should be called from `onCreateView(...)` instead of `onCreatePreferencesFix(...)`. Doing otherwise will result in a warning being logged to the logcat.
