### ISSUE TITLE
Popup menu android doesn't work correctly

### ISSUE THREAD

**Issue by AshtonYoon** [Gericop/Android-Support-Preference-V7-Fix#202]
I'm using AppCompat 28.0.0.3 

Below code is showing popup menu. (Xamarin.Android)

```
var popup = new Android.Support.V7.Widget.PopupMenu(activity, anchor);
var menu = popup.Menu;

menu.Clear();

menu.Add(Menu.None, 0, 0, "List").SetIcon(Resource.Drawable.ic_list);
menu.Add(Menu.None, 2, 2, "Cover").SetIcon(Resource.Drawable.ic_cover);

popup.MenuItemClick += (sender, e) =>
{
            var selectedService = (LayoutType)e.Item.ItemId;
            tcs.TrySetResult(selectedService);
};

var helper = new MenuPopupHelper(activity, (MenuBuilder)popup.Menu, anchor);
helper.SetForceShowIcon(true);
helper.Show();
```

When show a ``PopupMenu`` with ``helper.SetForceShowIcon(true);``, Icons padding are looks so strange.

It works correctly on AppCompat 27.0.2.1

![Screenshot_20191022-133852_Aurender](https://user-images.githubusercontent.com/16028154/67259552-6c126d80-f4d1-11e9-8a42-40746984a9f4.jpg)

Here is same problem

https://stackoverflow.com/questions/54424258/popup-menu-android-doesnt-work-correctly

![image](https://user-images.githubusercontent.com/16028154/67259565-7b91b680-f4d1-11e9-963d-49022bb5ddd8.png)

**Comment by gregkorossy** [comment]
What does it have to do with this lib? This seems to be a problem with the implementation you use.
