### ISSUE TITLE
AndroidX 1.1.0

### ISSUE THREAD

**Issue by RocketRider** [Gericop/Android-Support-Preference-V7-Fix#204]
Hello, I am using your lib in a big project and would like to upgrade to AndroidX release 1.1.0.
I made an issue in your new Project, but you did not answer there, are you still maintaining this lib?

https://github.com/takisoft/preferencex-android/issues/6

**Comment by gregkorossy** [comment]
Yeah, sorry, I forgot about that. Still need a thing to fix #203 before upgrading to 1.1.0. Also, this repo will be merged with that one at some point (more like redirected).

**Comment by gregkorossy** [comment]
Going to release v1.1.0 today without the fix for #203 for the time being as it needs some significant changes.

**Comment by gregkorossy** [comment]
@RocketRider Check out v**1.1.0** which has been released just now!

**Comment by RocketRider** [comment]
Thank you! :+1:
