### ISSUE TITLE
Show no divider above first preference

### ISSUE THREAD

**Issue by ben04** [Gericop/Android-Support-Preference-V7-Fix#21]
I built in this library so I can use a collapsing toolbar with a PreferenceFragment in the content area. So far I got everything working, unless one small thing: I can't remove the divider above the first preference. The result is, that the grey divider is directly beneath the yellow toolbar, which just doesn't look good...

![screenshot_20160523-164559](https://cloud.githubusercontent.com/assets/8714229/15474623/e461545c-2105-11e6-91a8-e52e7a77861b.png)

Just in case it's important, there are only Preferences on my PreferenceScreen.

**Comment by Gericop** [comment]
If I remember correctly, that line is there to show the upper boundary of the list. If you want to remove that, don't set `DIVIDER_PREFERENCE_BEFORE_FIRST` in `setDividerPreferences(...)`.

So, if you want to remove that while keeping the rest of them, just do this:
```java
setDividerPreferences(DIVIDER_PREFERENCE_BETWEEN | DIVIDER_PREFERENCE_AFTER_LAST)
```

**Comment by ben04** [comment]
Unfortunately that doesn't work...

Code snippet:

public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        
        super.onCreateView(inflater, container, savedInstanceState)
        addPreferencesFromResource(R.xml.information);
        setDividerPreferences(DIVIDER_PREFERENCE_BETWEEN | DIVIDER_PREFERENCE_AFTER_LAST);

        setupUrlMap();
        setupCurrentVersion();

        return super.onCreateView(inflater, container, savedInstanceState);
    }`

**Comment by Gericop** [comment]
Try putting `addPreferencesFromResource(R.xml.information)` into `onCreatePreferencesFix(...)`.

**Comment by xdgimf** [comment]
Hi, I notice that when using ````setDividerPreferences(DIVIDER_PREFERENCE_BETWEEN | DIVIDER_PREFERENCE_AFTER_LAST)````, instead of adding specific dividers it doesn't add anything.

````
super.setDivider(null);

            if (flags == DIVIDER_DEFAULT) {
                divPrefFlags = DIVIDER_PREFERENCE_BETWEEN;
            }

            if (divItemDecoration == null) {
                divItemDecoration = new DividerItemDecoration(getDividerDrawable()); // getDividerDrawable returns null
                recyclerView.addItemDecoration(divItemDecoration);
            }
````

I checked why it doesn't shows the dividers and found out that ````getDividerDrawable()```` returns null

**Comment by Gericop** [comment]
@xdgimf Okay, I know why `getDividerDrawable()` returned null. Updated library to 23.4.0.4, that should fix your problem.

**Comment by Gericop** [comment]
@ben04 Does your problem still exist?

**Comment by ben04** [comment]
Nah, it was fixed by updating to the newest library version. 
Thanks for your help, Gericop! 👍
