### ISSUE TITLE
PreferenceFixTheme.DayNight.DarkActionBar

### ISSUE THREAD

**Issue by alexandrucene** [Gericop/Android-Support-Preference-V7-Fix#23]
I think we need also a PreferenceFixTheme.DayNight.DarkActionBar theme. Without it, I have to create manual Toolbar and style it to match the desired design.

**Comment by Gericop** [comment]
Committed a new version: 23.4.0.5. Check it out, it should have the DarkActionBar variant there.

**Comment by alexandrucene** [comment]
It's working great, thanks!
