### ISSUE TITLE
problems when rendering layout

### ISSUE THREAD

**Issue by amgdeveloper** [Gericop/Android-Support-Preference-V7-Fix#24]
In your sample project, when trying to rendering the layout it crashes, so I neither cannot use it in other projects.  

![crash](https://cloud.githubusercontent.com/assets/19927275/16038979/c2b4bfa0-3227-11e6-94b5-ebb458ccdb40.jpg)

**Comment by Gericop** [comment]
This seems to be a problem(?) with the support library itself. Just ignore this warning, the rest of the layout should work fine.

**Comment by amgdeveloper** [comment]
The problem is that if I set as the app theme on PreferenceFix themes I cannot preview the layout,

**Comment by Gericop** [comment]
Try changing the API level to lower than 22 in the preview window. It seems like API 22+ displays this error if one uses AppCompat themes (which the `PreferenceFixTheme` is based on).

**Comment by Gericop** [comment]
In Android Studio 3.0 Canary 9 the rendering works fine with API 26.
