### ISSUE TITLE
PreferenceCategory bottom margin too big

### ISSUE THREAD

**Issue by nairbspace** [Gericop/Android-Support-Preference-V7-Fix#26]
First of all, great library! I don't think this is a bug directly for your library, but maybe can add it as a fix? See the comparison below using the regular PreferenceFragment, PreferenceFragmentCompat (using v14 theme), and your PreferenceFragmentCompat respectively. 

![comparison](https://cloud.githubusercontent.com/assets/15527175/16366691/dcbdf8b0-3bcf-11e6-9940-a0bfee43e402.png)

I've tried setting my own `android:listSeparatorTextViewStyle` and `Preference_TextAppearanceMaterialBody2` with 0 bottom margin/padding and it doesn't seem to fix it.

Any idea what's causing this issue? Thanks for all the work you put in.

**Comment by Gericop** [comment]
The latest version (v24.0.0) of the official library seems to be messing with the paddings / margins (that's why I didn't release the v24 fix yet), maybe they realized the same things you did and tried to fix it, with no success. I'll look into it anyways.

**Comment by nairbspace** [comment]
Oops forgot to mention this was on `v23.4.0`.

**Comment by Gericop** [comment]
Don't worry, I got it. I'm just saying that the support lib dev team is definitely doing something with the paddings / margins, so your problem maybe won't exist in the future versions. Or they just really messed up the layout this time.

**Comment by Gericop** [comment]
It's now available in 24.0.0.1. You can set the bottom margin to 0dp (or whatever you want) by setting `preferenceCategory_marginBottom` in your theme, for example:
```xml
<item name="preferenceCategory_marginBottom">0dp</item>
```

**Comment by nairbspace** [comment]
Tested and working. Nicely done! Thank you for the fix.

**Comment by giccisw** [comment]
Is this still working? I am not sure if I did something wrong or it is no longer supported...

**Comment by Gericop** [comment]
@giccisw It should. What's wrong?

**Comment by chenxiaolong** [comment]
I just submitted a fix for this upstream. https://android-review.googlesource.com/c/platform/frameworks/support/+/588653
