### ISSUE TITLE
Reflection solution on support library v24.0.0 does work well with inner preference page

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#27]
Hi @Gericop ,

I tried to add the following information on the already closed ticket - https://github.com/Gericop/Android-Support-Preference-V7-Fix/issues/25 

However, I'm not sure whether you will get notified. Since I found no way to contact you, I try to create a new ticket. I hope that is fine for you.

I realize the reflection solution doesn't work fine for inner preference page.

![0](https://cloud.githubusercontent.com/assets/308276/16663848/55fc167e-44b0-11e6-8d4b-597043384331.png)

![1](https://cloud.githubusercontent.com/assets/308276/16663859/5a6cff5c-44b0-11e6-96fe-07aef93fdf75.png)

Here's the XML for the preference screen - https://gist.github.com/yccheok/4172d782249757b1153cee9edd4c566b

Thanks.

p/s I like the work u had done on this project. In order to show my appreciate, I would like to donate to this project. May I know, does your project accept paypal donation? Thanks.

**Comment by Gericop** [comment]
Yeah, I received the other notification too, but I had no time to respond, sorry.
I tested it and looks good to me on API 17. What's your `onPreferenceStartScreen(...)` implementation? Also, which Android version is this?

Thanks, but I don't do this project for the money, I use this fix in my apps too. The bugs are really frustrating but also challenging, which I like. So it's a love-hate relationship :smile:

**Comment by yccheok** [comment]
The screenshot I posted is for API 16.

Just now, I re-test again using API 17, the inner screen is still having same padding problem shown in screenshots.

@Gericop 

You get the right catch! When I look back at the code

    // Code for public class JStockPreferenceActivity extends AppCompatActivity implements PreferenceFragmentCompat.OnPreferenceStartScreenCallback

    // http://stackoverflow.com/questions/32487206/inner-preferencescreen-not-opens-with-preferencefragmentcompat/32540395#32540395
    @Override
    public boolean onPreferenceStartScreen(PreferenceFragmentCompat preferenceFragmentCompat, PreferenceScreen preferenceScreen) {
        FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
        JStockInnerPreferenceFragmentCompat fragment = new JStockInnerPreferenceFragmentCompat();
        Bundle args = new Bundle();
        args.putString(PreferenceFragmentCompat.ARG_PREFERENCE_ROOT, preferenceScreen.getKey());
        fragment.setArguments(args);
        ft.add(R.id.content, fragment, preferenceScreen.getKey());
        ft.addToBackStack(preferenceScreen.getKey());
        ft.commit();
        return true;
    }

Then, I realize my `JStockInnerPreferenceFragmentCompat` is as follow

    public class JStockInnerPreferenceFragmentCompat extends PreferenceFragmentCompat

When I change to 

    public class JStockInnerPreferenceFragmentCompat extends PreferenceFragmentCompatFix

It works perfectly fine now. Sorry. I will close this ticket. It is no longer valid.

p/s I did not use your new gradle dependency. Your old code works just fine for me. Since nothing broken, I will avoid from changing the code :)

**Comment by Gericop** [comment]
I think you should give it a try though. The "Fix" suffix is no longer required (indeed, it's deprecated) as in my package there are same-name replicas of the broken classes and I "hacked" the `PreferenceManager` in a way that it loads those classes instead of the broken ones.

**Comment by yccheok** [comment]
Before running proguard, everything works fine including API 16.

I realize padding information is gone in API 16, after I export the app to APK (running proguard).

I added the following in proguard.

    # https://github.com/Gericop/Android-Support-Preference-V7-Fix/issues/30
    -keep class android.support.v7.preference.PreferenceGroupAdapter {
        *;
    }

Strangely. The padding information still gone. I check on the error log message. I expect to see some exception being thrown. However, there's no exception related to reflection.

Any idea?
