### ISSUE TITLE
Update this library with version 23.1.0 of the android support libraries.

### ISSUE THREAD

**Issue by bkhall** [Gericop/Android-Support-Preference-V7-Fix#3]
Hopefully the issues you discovered in 23.0.1 have been fixed.

**Comment by Gericop** [comment]
Haven't tried it yet but I know for sure that the EditTextPreference is even worse as they removed (*for whatever reason*) all the other methods too.

**Comment by Gericop** [comment]
So, I just checked out the new 23.1.0 support lib.

**Fixed:**
- background selector is now set
- the list dialog's wrong-side-of-radio-buttons bug
- preference titles aren't oversized anymore

**Not fixed:**
- `@style/PreferenceThemeOverlay` (i.e. the v7 compatible one) is still not material
- app still crashes if a dialog is open and you rotate the device
- pre-lollipop devices still don't use the accent color for the preference categories
- the categories are not in italic anymore, but they are also not bold yet

Also they messed up a little bit more the EditTextPreference things so you need to upgrade the custom classes to the latest ones.
