### ISSUE TITLE
Divider settings are not applied when returning from backstack

### ISSUE THREAD

**Issue by acleu** [Gericop/Android-Support-Preference-V7-Fix#34]
The problem can be demonstrated using the sample app. Just uncomment the setDividerPreferences() call in MyPreferenceFragment.onCreateView() and set the dividers to DIVIDER_NONE.

When the app is started, dividers are correctly hidden. Then press "PreferenceSrceen test" and return from the subscreen. The dividers are not hidden anymore.

I test this on a Nexus 7/2013, Android 6.0.1

Apparently, when the fragment is restored, the check "divPrefFlags == flags && !divPrefInvalid" in setDividerPreferences() is true and thus, the divider preferences are not applied.

**Comment by Gericop** [comment]
Thanks for the report. It's fixed now though haven't been committed yet. Stay tuned.

**Comment by Gericop** [comment]
Published v24.1.1.1 of the lib which contains the bugfix.

**Comment by acleu** [comment]
Wow. Great support. Incredibly fast.

I can confirm that it works now.
