### ISSUE TITLE
Smaller margin on API 19 compared to API 22 and 23

### ISSUE THREAD

**Issue by rfgamaral** [Gericop/Android-Support-Preference-V7-Fix#35]
As they say, a picture is worth a thousand words...

![emulators_margin](https://cloud.githubusercontent.com/assets/96476/17566773/ab7e0e42-5f34-11e6-9011-30772be2c769.png)

On API 22 (probably 21 too) and 23 the margin seems alright, but on 19 not so food. There's not much breathing space on the left side. Any thoughts on how to fix this locally or would I have to wait for a possible fix on this library?

Although this does not look good to me, could this be the expected behavior?

**Comment by Gericop** [comment]
I'll look into it. Do you use any dividers or anything?

**Comment by rfgamaral** [comment]
Really appreciated but please don't waste your time, it was a bug on my end. So sorry about this.

I have various build types and I was applying `PreferenceFixTheme` to just one of the build types (the only one which is using preferences, it's a debug module only available in the debug build type) which was inheriting styles from the main folder and for some reason they were not being applied correctly.

Just changed the base theme on the main folder to also use the `PreferenceFixTheme` and the problem fixed itself.
