### ISSUE TITLE
Different background color on API 22 compared to API 19 and 23

### ISSUE THREAD

**Issue by rfgamaral** [Gericop/Android-Support-Preference-V7-Fix#36]
As they say, a picture is worth a thousand words...

![emulators_margin](https://cloud.githubusercontent.com/assets/96476/17566773/ab7e0e42-5f34-11e6-9011-30772be2c769.png)

On API 19 and 23 the background color looks good, the white I specified as `<item name="android:windowBackground">@android:color/white</item>` on my application theme. But it looks odd on API 22 (probably 21 too). Any thoughts on how to fix this locally or would I have to wait for a possible fix on this library?

Although this does not look good to me, could this be the expected behavior?

**Comment by rfgamaral** [comment]
Not sure if a similar issue on my end as I explained on #35 but I fixed this by adding `<item name="android:colorBackground">@android:color/white</item>` to my base theme.

Not sure if this can be considered an issue with this library so I'll leave the decision to close this to you.

Sorry if this is another of my stupid problems... :(

**Comment by Gericop** [comment]
I think it's a platform difference. I didn't set any of these arguments in the fix themes, so I guess it's just Android thingy.
