### ISSUE TITLE
Cannot set accent color

### ISSUE THREAD

**Issue by NicoDreamzZ** [Gericop/Android-Support-Preference-V7-Fix#37]
Hey there,

i want to change the accent color to a different color as the default accent color in the rest of my activity.
Adding `<color name="accent">#ff4081</color>
    <color name="preference_accent">@color/accent</color>` to my colors.xml doesn't fix it :(

Is there a other way to overwrite the accentcolor only for the preference fragment?

**Comment by Gericop** [comment]
Setting only the `preference_accent` should be enough. What do you see on the screen? Could you make a screenshot?

**Comment by Gericop** [comment]
Oh, wait. Do you use this theme as your main theme? So, you probably override `colorAccent` in your styles file, right? Well, if you do so, it will automatically set the accent color to that value and there's currently no way to change this behavior. You can either use a separate theme for your preferences fragment (probably in a new activity) or just keep the same look-and-feel as the rest of your activity.

**Comment by NicoDreamzZ** [comment]
Hmm okay, thanks.

**Comment by Gericop** [comment]
As of v24.2.0.0, the `preference_accent` attribute is no longer in use. Make sure your theme has a `colorAccent` set to an appropriate value.
