### ISSUE TITLE
Crash in ListPreference during rotation

### ISSUE THREAD

**Issue by proninyaroslav** [Gericop/Android-Support-Preference-V7-Fix#39]
Hello. If you rotate device 2 times with the open  dialog then occurs crash:
```
java.lang.IllegalStateException: Failure saving state: ListPreferenceDialogFragmentCompat{9d3f3e08 #1 android.support.v7.preference.PreferenceFragment.DIALOG} has target not in fragment manager: SettingsFragment{9d3f3c08}
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1935)
at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:568)
at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
at android.app.Activity.performSaveInstanceState(Activity.java:1153)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3712)
at android.app.ActivityThread.access$900(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Gericop** [comment]
Is it possible you are using it from a <fragment> tag in a layout XML? The sample app doesn't crash.

**Comment by proninyaroslav** [comment]
My example:
``` XML
<android.support.v7.preference.PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v7.preference.ListPreference
        android:title="Download Details"
        android:summary="Select the kind of data that you would like to download"
        android:key="downloadType"
        android:defaultValue="1"
        app:entries="@array/listArray"
        app:entryValues="@array/listValues" />
</android.support.v7.preference.PreferenceScreen>
```

**Comment by Gericop** [comment]
I see the problem: don't use fully qualified package name. It's not recommended in the original implementation either, and causes troubles in the fix because the PreferenceManager normally resolves the preferences using the fixed classes available in my fix package, then, if it can't find there, in the original packages. By specifying the package name in your XML you effectively eliminate this behavior which can result in crashes, what you had just experienced.

**Comment by proninyaroslav** [comment]
Alas, it didn't help.

**Comment by Gericop** [comment]
Try the sample app here, it should work.

Also, please provide your device type and/or Android version. How do you instantiate and add your `Fragment` to the `FragmentManager`?

**Comment by proninyaroslav** [comment]
Android 4.4 - 6.1 (all in range).
I added fragment the following way:
```
getSupportFragmentManager().beginTransaction()
                .replace(R.id.fragment_container, fragment).commit();
```
Fragment class:
```
public class StorageSettingsFragment extends PreferenceFragmentCompat
{
    public static StorageSettingsFragment newInstance()
    {
        StorageSettingsFragment fragment = new StorageSettingsFragment();

        Bundle args = new Bundle();
        fragment.setArguments(args);

        return fragment;
    }

    @Override
    public void onCreatePreferencesFix(Bundle savedInstanceState, String rootKey)
    {
        addPreferencesFromResource(R.xml.pref_storage);
    }
}
```

**Comment by Gericop** [comment]
I see the problem and is not related to this library nor any other libs.
The problem is the way you create / use your `StorageSettingsFragment`. You probably use the fragment adder in a similar manner in your `Activity`:
```java
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	
	// [...]

	StorageSettingsFragment fragment = StorageSettingsFragment.newInstance();

	getSupportFragmentManager().beginTransaction()
                .replace(R.id.fragment_container, fragment).commit()
}
```

The problem with this is that when you rotate your phone, a new fragment gets created every time which replaces the old one. This won't crash until you have a child fragment of that fragment (in this case it's `ListPreferenceDialogFragmentCompat`) which has the old fragment as a target set.

To solve the problem, you just have to check whether it's the first time `onCreate(...)` is called. It's pretty simple with the received argument of `savedInstanceState`. If it's null, it's the first time. Nice, huh? In your case, the actual fix looks like this:
```java
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	
	// [...]

	if (savedInstanceState == null) {
		StorageSettingsFragment fragment = StorageSettingsFragment.newInstance();

		getSupportFragmentManager().beginTransaction()
                .replace(R.id.fragment_container, fragment).commit()
	}
}
```

**Comment by proninyaroslav** [comment]
Yes, you're almost right. Now code works correctly. Since the Support Library doesn't support two-pane interface, I write your implementation for application. Preference opens in activity or replaced in the main window container.

P.S: I've got one more question about `activatedBackgroundIndicator`, so as not to open a new issue, I will write it here:
the only difficulty I encountered - highlighting the selected preference item (aka header in PreferenceActivity).
For example (Email app):
![screenshot_20160819-134331](https://cloud.githubusercontent.com/assets/7840559/17831971/125c5bf6-6709-11e6-9b5c-d0230cd86329.png)
Is it possible to provide this opportunity in PreferenceFragmentCompat?

**Comment by Gericop** [comment]
Well, the `PreferenceFragmentCompat` is built on top of a `RecyclerView` which provides no method for setting the list selection. There are multiple problems to solve:

1. The selected item position has to be stored and applied in `onBindViewHolder(...)` of `PreferenceGroupAdapter` using `View.setSelected(...)` on the item view
2. The `selectableItemBackground`, which is used as a background drawable on preferences, has no selector for "[state_selected](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable.html#attr_android:state_selected)" state, thus a new `LayerList` drawable is needed to accommodate both this and the desired drawable (preferably a color one in your case).
3. This still cannot change the text color of the preferences. Applying only the background with, for example, the accent color makes the background color change when one sets selection but the preference's text color stays the same, which may look wrong. This can be resolved manually by iterating over the children of the preference's root view and setting the text color to an appropriate one, like using a `ColorStateList`.

I tested it so it's possible to create such a thing, though I don't know whether it should be part of this lib or not.

**Comment by proninyaroslav** [comment]
Thanks for the tip. I'll try to do either.
