### ISSUE TITLE
[Android Studio]Can't see layout preview when I use android.support.v7.preference

### ISSUE THREAD

**Issue by MirlanMaksv** [Gericop/Android-Support-Preference-V7-Fix#41]
I can't see layout preview of file in xml folder when I use `preference-v7`
I have tried to clean&rebuild, invalidate caches&restart, still can't see preview 
![no](https://cloud.githubusercontent.com/assets/20371099/18045880/ef329e8e-6df6-11e6-9de9-8eb1a79ba126.png)
![yes](https://cloud.githubusercontent.com/assets/20371099/18045881/ef34c178-6df6-11e6-9a7f-16473316ff4d.png)

**Comment by Gericop** [comment]
Don't use fully qualified names in the XML. It was never needed and it still isn't. There are some hacks that rely on the pure class name (e.g. `ListPreference`) as it's being redirected to a different class, not the `android.support.v7.preference` one.

**Comment by MirlanMaksv** [comment]
@Gericop yes I have tried to use without full names, but in that case it's showing me old preferences(in KitKat instead of new switches, old ones), I don't like how they look. How can I use new beautiful preferences without writing their full names? (I am not so long in programming)

**Comment by Gericop** [comment]
Are you using `PreferenceCompatFix` as your fragment's base class?

**Comment by MirlanMaksv** [comment]
aaaaa(, I think I was using the official one, I will try to switch to FIX now

**Comment by Gericop** [comment]
Is this issue still present?
