### ISSUE TITLE
Style of dialog message in EditTextPreference

### ISSUE THREAD

**Issue by proninyaroslav** [Gericop/Android-Support-Preference-V7-Fix#42]
Hello. Style of dialog message is very different from Material, since there is no padding and too small fonts:

![screenshot_20160824-201222](https://cloud.githubusercontent.com/assets/7840559/18137390/2d0bb222-6fb9-11e6-983b-cab27429ee7d.png)
Is it possible to change style?

For example, a simple AlertDialog:
![screenshot_20160831-191919](https://cloud.githubusercontent.com/assets/7840559/18137501/958b5a82-6fb9-11e6-8455-97296769bdfe.png)

**Comment by Gericop** [comment]
What version of Android is this?

**Comment by proninyaroslav** [comment]
Android 4.0 - 7.0 (in range).

**Comment by Gericop** [comment]
Yeah, Google did this in the official lib. I'll look into it whether it can be fixed without recreating a lot of stuff.

**Comment by yccheok** [comment]
Hi,

Same problem here. I am using

        <EditTextPreferenceFix
            android:key="STOCK_ALERT_EMAIL"
            android:title="Stock alert email"
            android:dialogTitle="Stock alert email" />

with the following support library version

    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.takisoft.fix:preference-v7:25.0.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'com.android.support:recyclerview-v7:25.1.0'

Here's what I'm getting

![screenshot_20170105-001213](https://cloud.githubusercontent.com/assets/308276/21649310/326e7e6c-d2dc-11e6-8c41-f7060a679e9e.png)

The dialog padding is too small, I think...

**Comment by Gericop** [comment]
Yeah, this is the standard Google way for the support lib... I'll try to fix that if it's possible without recreating the layout.

**Comment by Gericop** [comment]
Is this better?
![screenshot_1484502923](https://cloud.githubusercontent.com/assets/5181621/21964862/3b92b46a-db54-11e6-9103-a7ce480f118a.png)

**Comment by Gericop** [comment]
Fixed in **v25.1.0.1**.

**Comment by yccheok** [comment]
Sorry for late reply. It looks good to me. Going to use the latest version in my app.
