### ISSUE TITLE
EditTextPreference does not store in the correct type

### ISSUE THREAD

**Issue by joshuaavalon** [Gericop/Android-Support-Preference-V7-Fix#45]
```
<EditTextPreference
	android:defaultValue="200"
	android:inputType="number"
	android:key="limit"
	android:summary="title"
	android:title="content" />
```

When I use 
```
final SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
return preferences.getInt("limit", 200);
```

It throws `java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer`.

**Comment by Gericop** [comment]
`EditTextPreference` (and all the `Preference` descendants) store values as strings, no matter what. Use `getString(...)` and parse the string using `Integer.parseInt(...)`.
