### ISSUE TITLE
Some question on build.gradle

### ISSUE THREAD

**Issue by yccheok** [Gericop/Android-Support-Preference-V7-Fix#47]
Hi Gergely Kőrössy,

Sorry for that! Since I don't find any better channel to contact you to ask about non-project thingy, I decide to open this issues in order able to ping you.

Recently, I wish to fork some Android library projects from GitHub, perform some modification, publish to maven (or jcenter) for my own usage purpose.

So that I can use them by having the following in my build.gradle

    compile 'com.yccheok:my-forked-library-v7:24'

After reading https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

I expect I shall saw some similar info in your [build.gradle](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/build.gradle)

	apply plugin: 'com.android.library'
	ext {
		bintrayRepo = 'maven'
		bintrayName = 'fb-like'

		publishedGroupId = 'com.inthecheesefactory.thecheeselibrary'
		libraryName = 'FBLike'

However, I found none. They just seem like a normal build.gradle for non-library project.

May I know what is the secret behind, of publishing your `Android-Support-Preference-V7-Fix` library?

Thank you very much!
Cheok

**Comment by Gericop** [comment]
@yccheok It's in the preference-v7 module: https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/preference-v7/build.gradle

**Comment by yccheok** [comment]
@Gericop Wow. Thanks for the speedy respond. My bad! I should check more carefully. Thank you very much.
