### ISSUE TITLE
Add @Nullable annotations to parameters

### ISSUE THREAD

**Issue by tylerwilson** [Gericop/Android-Support-Preference-V7-Fix#48]
I am using your lib fine in Java, then I switched to use Kotlin. I was then getting an exception in the OnCreate method because the savedInstanceState Bundle was not marked as @Nullable, but it was coming in as null from the OS.

I added overrides via the IDE (Android Studio 2.2) but it would likely be better if your source included the annotations directly.

An interesting item is that I see the android PreferenceFragmentCompat does not include the @Nullable, but its superclass - Fragment - does include it. So I think it is a bug in the Android SDK too.

**Comment by Gericop** [comment]
Added `@Nullable` to a few methods, it's available from v24.2.1.1. Please, test it with Kotlin.

**Comment by Gericop** [comment]
@tylerwilson Did you test it?
