### ISSUE TITLE
How to style dialog from DialogPreference

### ISSUE THREAD

**Issue by tylerwilson** [Gericop/Android-Support-Preference-V7-Fix#52]
I apologize if this is not directly related to Preference-V7-Fix - though perhaps it is something it could assist with in the future.

I have been trying to style the popup dialogs from ListPreference, but nothing is working. I have tried overriding dialogPreferenceStyle, alertDialogStyle, etc. but it is always ignored. (I changed my main preferences to use a dark background and white text, which then causes many of the text and controls in the dialogs to be white and white and thus invisible).

Is there an global dialog style in the Fix lib that might help be accomplish this?

**Comment by giccisw** [comment]
I lost a lot of time trying to figure how to implement this and at the result is quite simple, if you just want all the dialogs to have the same style.

Set a theme like this to the activity implementing the preferences:

`<resources>

    
    <color name="preference_accent">@color/app_accent</color>

    
    <style name="AppThemePreferences" parent="@style/PreferenceFixTheme">
        <item name="colorPrimary">@color/app_primary</item>
        <item name="colorPrimaryDark">@color/app_primary_dark</item>
        <item name="colorAccent">@color/app_accent</item>
        <item name="android:windowBackground">@color/app_background</item>
        <item name="actionModeBackground">@color/app_action_mode_background</item>
        <item name="colorControlHighlight">@color/app_control_highlight</item>
        <item name="colorControlActivated">@color/app_control_activated</item>
        
        <item name="dialogTheme">@style/AppCompatDialog</item>
        <item name="alertDialogTheme">@style/AppCompatAlert</item>
    </style>

</resources>

    
    <style name="AppCompatDialog" parent="Theme.AppCompat.Dialog">
        
        <item name="android:textColorPrimary">@color/dialog_text</item>
        
        <item name="android:background">@color/dialog_background</item>
        
        <item name="colorAccent">@color/dialog_button</item>
        <item name="colorControlHighlight">@color/dialog_control_highlight</item>

        <item name="colorPrimary">@color/app_primary</item>
        <item name="colorPrimaryDark">@color/app_primary_dark</item>
    </style>

    
    <style name="AppCompatAlert" parent="Theme.AppCompat.Dialog.Alert">
        <item name="android:textColorPrimary">@color/dialog_text</item>
        
        <item name="android:background">@color/dialog_background</item>
        
        <item name="colorAccent">@color/dialog_button</item>
        <item name="colorControlHighlight">@color/dialog_control_highlight</item>

        <item name="colorPrimary">@color/app_primary</item>
        <item name="colorPrimaryDark">@color/app_primary_dark</item>
    </style>
`

Take the above code as an example as I took it directly from my app, but it is working properly for me.

**Comment by Gericop** [comment]
What @giccisw writes is the standard way of overriding `AlertDialog` styles. It was part of the lib as the `AlertDialog` wouldn't use the accent color from the main theme, but since has been removed in [v24.2.0.0](https://github.com/Gericop/Android-Support-Preference-V7-Fix/commit/a6082cb0a508f5e0305a626c9a2a841e943ef8f6#diff-483bbb12192b1b74adadc9b4076b203b) because the Android team fixed this behavior.

**Comment by tylerwilson** [comment]
So to be clear @Gericop: I should be able to set the background of the displayed AlertDialog that is displayed from any DialogPreference-derived Preference? Because I have not been able to effect any changes to the dialogs. I will be trying to tweak my existing style to match what @giccisw has above (I thought mine was pretty much the same, but it could be one character off I suppose).

**Comment by tylerwilson** [comment]
Okay, I got it working. Thank you both so much. I was using "android:alertDialogTheme" instead of the plain "alertDialogTheme". Frustrating. I also was not using the PreferenceFixTheme as a base for my Preference Theme which perhaps has an effect as well.

**Comment by dynoChris** [comment]
What is PreferenceFixTheme?
