### ISSUE TITLE
Issue with SwitchPreferenceCompat animation

### ISSUE THREAD

**Issue by rubensousa** [Gericop/Android-Support-Preference-V7-Fix#53]
After updating to 25.0.0.0, the animation of the switch is disabled :(. Reverting back to 24.2.1.0 fixes the problem

**Comment by Gericop** [comment]
What version of Android do you use?

**Comment by rubensousa** [comment]
I'm testing on API 22. Didn't test on another phone yet.

**Comment by Gericop** [comment]
I just tested it on API 23 (emulator) and it seems to be fine there.

**Comment by Gericop** [comment]
API 21 works too.

**Comment by rubensousa** [comment]
I don't know what happened, but I can't reproduce it anymore either :(. I'm going to close this.
