### ISSUE TITLE
Upgrade to support library v25.1.0

### ISSUE THREAD

**Issue by auchri** [Gericop/Android-Support-Preference-V7-Fix#57]

**Comment by Gericop** [comment]
Funny that the repo is available already, yet we have to wait for the revisions' webpage to refresh.

**Comment by Gericop** [comment]
According to the [issue tracker](https://code.google.com/p/android/issues/list?can=1&q=label%3ATarget-Support-25.1.0) there are no changes to the preferences lib nor anything closely related to it.

**Comment by Mygod** [comment]
There is a new class [`SeekBarPreference`](https://developer.android.com/reference/android/support/v7/preference/SeekBarPreference.html).

**Comment by caarmen** [comment]
For SeekBarPreference, it uses `textAppearanceMedium` text instead of `textAppearanceLarge` for the title.  I added this to my custom preference style in my project:
`<item name="android:textAppearanceMedium">?android:attr/textAppearanceListItem</item>`

**Comment by caarmen** [comment]
More on `SeekBarPreference`:  The left and right spacing looks incorrect on large screens.  I'm sure you'll find a proper workaround for this, but here's what I did:

In my preference xml file, I set `android:layout` to a custom layout, which wraps around the real layout file, adding a padding.  Here's what that layout looks like:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:paddingLeft="@dimen/seekbar_horizontal_padding_fix"
    android:paddingStart="@dimen/seekbar_horizontal_padding_fix"
    android:paddingRight="@dimen/seekbar_horizontal_padding_fix"
    android:paddingEnd="@dimen/seekbar_horizontal_padding_fix"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <include layout="@layout/preference_widget_seekbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</FrameLayout>
```

I set `seekbar_horizontal_padding_fix` to `0dp` by default, and to `8dp` in the `values-sw600dp` folder.  I chose this folder by trial and error: I couldn't figure out exactly how the margins/padding worked for other preference types.

**Comment by Gericop** [comment]
Sorry for the late response, I've been working on my thesis for the last couple weeks. I'll check out the new *bugs* and stuff soon.

**Comment by Gericop** [comment]
Okay, so just wtf. Do I see it correctly?
First of all, there's no `SeekBarPreference` in the android.preference package (so the "native" one is missing, someone [reported it](https://code.google.com/p/android/issues/detail?id=82028) already).
Second, the `SeekBarPreference` has no material layout. It's completely missing from the v14 package's `PreferenceThemeOverlay.v14.Material` style. Seriously, this is really annoying. Google has lost quality control for the support lib...

**Comment by Mygod** [comment]
I think the first one is intended since there isn't a native RecyclerView nor a native DropdownPreference either (a similar one can only be found in the settings app package).

**Comment by Gericop** [comment]
I don't think it's intended since the support `SeekBarPreference` [references it](https://developer.android.com/reference/android/support/v7/preference/SeekBarPreference.html) in the description.

**Comment by Gericop** [comment]
Reported the wrong text size: [issue 230920](https://code.google.com/p/android/issues/detail?id=230920)
Reported the missing material styles: [issue 230922](https://code.google.com/p/android/issues/detail?id=230922)

**Comment by Gericop** [comment]
@caarmen Can you show me a screenshot of the bad padding? I'm looking at the values and the layout, and it seems to be set to a fixed value of 0dp padding on the start, 22dp padding on the end, and the value is 36dp wide. I can't see different values set for different qualifiers.

**Comment by caarmen** [comment]
Sorry for the delay!  Here's a screenshot from a Google emulator (Nexus 10)

![screenshot_1483908268](https://cloud.githubusercontent.com/assets/1731388/21753352/b6e78aa0-d5eb-11e6-8ab4-5f7af9b60bbb.png)

The "voice speed" setting doesn't have the custom layout.
The "voice pitch" setting has the custom layout.

**Comment by Gericop** [comment]
Sorry for the late reply, I had to take my final exam, so now I'm back as a Master of Science in Software Engineering :)
How is that possible that your original `SeekBarPreference` value is not clipped? On a Nexus 10 emulator screen it looks like this to me:
![clipped](https://cloud.githubusercontent.com/assets/5181621/21956443/1a3f478e-da81-11e6-82de-b804f2f7023c.png)

**Comment by caarmen** [comment]
Congrats @Gericop on becoming a master :)

I think the clipping was solved with the change in this comment: https://github.com/Gericop/Android-Support-Preference-V7-Fix/issues/57#issuecomment-267549521

> For SeekBarPreference, it uses `textAppearanceMedium` text instead of `textAppearanceLarge` for the title. I added this to my custom preference style in my project:
> ```
> <item name="android:textAppearanceMedium">?android:attr/textAppearanceListItem</item>
> ```

**Comment by Gericop** [comment]
@caarmen Yeah, I though so. This whole layout is just messed up. I also noticed that the SeekBar in your layout is aligned with the title of the preference. Did you set anything else? It has some left padding both in emulator and on real device.

**Comment by caarmen** [comment]
I think my `seekbar_horizontal_padding_fix` fixed that alignment, if I remember right. You can take a look at the project I have with the SeekBar if that could help: https://github.com/caarmen/poet-assistant

**Comment by Gericop** [comment]
Did you try it on API 17 or lower device? When you grab the thumb of the seek bar and move it to zero (from a higher value, so that the thumb wouldn't touch the left side initially), it gets clipped, and it only gets resolved, when you move the list up or down (probably through the invalidation phase).

**Comment by caarmen** [comment]
I didn't notice this clipping behavior.  Here's a screen recording from an api 16 emulator.  Note, I haven't applied many prefs fixes to this screen: I still have the large font for the titles, for example.

![output](https://cloud.githubusercontent.com/assets/1731388/21958226/bd37ef9a-daa9-11e6-8f61-95e4294bf604.gif)

**Comment by Gericop** [comment]
The clipping is not present, because the seek bar is not aligned with the title (you can see it has a little padding on the left).
Here's what can be seen after the thumb has been moved back to the 0 position (the blue lines are the layout bounds, don't mind them).
![untitled](https://cloud.githubusercontent.com/assets/5181621/21958940/7f08d5d0-dab9-11e6-9114-025157ed930e.png)

**Comment by Gericop** [comment]
Can't really decide whether to align it with the title. To align the seek bar with the title, some serious work is required due to how the layout is built (possibly including a new `SeekBarPreference` class extending the original one to handle the padding / negative margin issue...

**Comment by Gericop** [comment]
Found a way to fix the alignment. It is fully functional and aligned.
