### ISSUE TITLE
Wrong horizontal padding on api 17, 18 and 19

### ISSUE THREAD

**Issue by oakkitten** [Gericop/Android-Support-Preference-V7-Fix#6]
Doesn't affect 15, 16, 21, 22

![shot-151111-023347-r 1](https://cloud.githubusercontent.com/assets/1710718/11080514/0cc96efc-881d-11e5-8731-2d8c7cc3cfe9.png)

**Comment by Gericop** [comment]
Fixed, see the [latest commit](https://github.com/Gericop/Android-Support-Preference-V7-Fix/commit/edde218c5d51e34cbf24b4e8ce027810ec5e916c).
