### ISSUE TITLE
SwitchPreferenceCompat visual appearance problems on 160 dpi screens

### ISSUE THREAD

**Issue by phillat** [Gericop/Android-Support-Preference-V7-Fix#61]
The visual appearance of the switch_thumb on my huawei y220 (api 10) is not properly aligned on the switch_track. On my phone (api 10) the switch thumb is kind of shifted a little to the bottom. Below is a screenshot of my phone and a friend's nokia x phone (api 16).

## Update
I installed the app on another phone running api 17 and the appearance of the switch widget was the same as my phone (api 10). I did, however, notice one common denominator--the screen size! Both phones had a screen height of 480 pixels and width of 320 pixels (160 dpi). Maybe this observation could help.

**Appearance of switch on my huawei y220 (api 10):**
![huawei_y220_api_10](https://cloud.githubusercontent.com/assets/25318585/22256170/df22837c-e251-11e6-8655-e500023a5ce7.png)

**Appearance of switch on nokia x (api 16):**
![nokia_x_api_16](https://cloud.githubusercontent.com/assets/25318585/22256243/1d40ec20-e252-11e6-937d-803fc7a9bde1.png)

**Comment by phillat** [comment]
## Update two
I think it's not really a bug because when I connect the api 17 phone (160 dpi) to my pc and build and run the application on it the switch looks properly aligned. I then transferred the app to my phone (also 160 dpi) and an infinix note 2 (1184x720 320 dpi) the switch still looks great on both phones but not on the nokia x (240 dpi). Basically, when I build and run on a 160 dpi device and transfer the app to another 160 dpi or the 320 dpi infinix the switch looks properly aligned but not a 240 dpi screen conversely when I build and run on the 240dpi phone and transfer it to the 320dpi infinix the switch is properly aligned but not on the 160dpi phones. So I think it really has nothing to do with screen density or api level but probably the build process determining the screen density and aligning the switch_thumb properly. 

One thing I'm a little concerned about is whether or not it will cause problems if I build and publish a release version of an app on play store since essentially one is downloading the apk from the play store. Anyway, I'm sorry if I probably wasted your time sending you on a wild goose chase. I'll wait for your response before closing the issue.

**Switch properly aligned on huawei 160dpi:**

![hawei proper](https://cloud.githubusercontent.com/assets/25318585/22272174/6cf901ba-e290-11e6-8ef0-04631dedafc1.png)


**Apperance of switch misaligned on the the nokia x 240dpi:**

![nokia problem](https://cloud.githubusercontent.com/assets/25318585/22272206/a925300a-e290-11e6-8b43-c8bf3a881910.png)

**Comment by Gericop** [comment]
You should not transfer the debug APKs built for one phone because they might contain only the files qualified for the target device. You can check proper builds by building a signed APK or a debug APK from the *Build* menu in Android Studio.

**Comment by phillat** [comment]
Thank you, for your feedback. I didn't know when I clicked run the debug APK is tailor built for the  phone currently connected. Thanks once again.
