### ISSUE TITLE
Feature Request: Add RingtonePreference

### ISSUE THREAD

**Issue by opus1269** [Gericop/Android-Support-Preference-V7-Fix#64]
Great library, thanks!

Would be nice to have RingtonePreference.
The [workaround](https://code.google.com/p/android/issues/detail?id=183255)  is fine, but lots of extra code.

**Comment by Gericop** [comment]
This library's primary goal is to address the issues found in the official preference-v7 implementation. As such, I'd rather not extend it with new functions. However, later I might create an extended artifact that would be built on top of the bugfix library and could contain several additions, but it won't happen in the next few months.

**Comment by Gericop** [comment]
Is this still wanted? Anymore types of preferences that would be great (e.g. date picker)?

**Comment by DreaminginCodeZH** [comment]
Yes, still wanted. And I believe the PreferenceManager.startAcitivityForResult() can be implemented in a headless `Fragment` in `onDisplayPreferenceDialog()`.

**Comment by Gericop** [comment]
Wouldn't it be better to have something like a `ListPreference`? So not in a separate Activity but a simple dialog.

**Comment by DreaminginCodeZH** [comment]
But it is a system activity - didn't want to port such a large portion of code.

**Comment by Gericop** [comment]
It's not that difficult. Also, the system Activity wouldn't have the same design (color scheme) as the rest of the app, which is not good in my opinion.

**Comment by DreaminginCodeZH** [comment]
Yes, but that's even how the native `RingtonePreference` behaves. Should we diverge from that as a support library?

**Comment by Gericop** [comment]
I think it would look better if the dialog had the same color scheme as the rest of the app. Other than this there would be no difference in the behavior so I think it's a fair trade. I cannot really see anyone complaining about the dialog having the same design as other parts of the screen instead of something completely different (e.g. you use dark theme in your app but the system one is light themed).

**Comment by Gericop** [comment]
By the way, this will be included in a separate artifact that might be used for adding new preference types.

**Comment by Gericop** [comment]
Well, I implemented it mostly, the only "problem" is that the `RingtoneManager` has no methods for setting default / silent items enabled in the cursor. I can add them to the list, but there's no publicly available, built-in translation for "Default" and "None" (or "Silent"). This means that either the user has to provide the strings somewhere or I need to look up these values and include them for all possible locales.

**Comment by Gericop** [comment]
Uploaded an experimental version to jCenter. Try with
```
compile 'com.takisoft.fix:preference-v7:26.0.1.1-alpha1'
compile 'com.takisoft.fix:preference-v7-extras:26.0.1.1-alpha1'
```

Note that the translations are missing for the following strings:
- Default ringtone; Default notification sound; Default alarm sound;
- Ringtone _(the dialog title)_
- None

I'll add them later on to the artifact, but I need to collect them from different sources (for whatever reasons they are scattered through the framework and the media providers).

**Comment by Gericop** [comment]
@opus1269 and @DreaminginCodeZH The translations have been uploaded too, so theoretically the `RingtonePreference` is fully functioning now. Check out the latest releases:

```gradle
compile 'com.takisoft.fix:preference-v7:26.0.1.1-alpha2'
compile 'com.takisoft.fix:preference-v7-extras:26.0.1.1-alpha2'
```

> You might have to add the following repo to your `repositories` in order to access the new package until it gets released properly: `maven { url "http://dl.bintray.com/gericop/maven" }`)

![device-2017-08-20-205842](https://user-images.githubusercontent.com/5181621/29497554-6ab47daa-85ea-11e7-831c-45d0bbf377a7.png)

**Comment by easypro** [comment]
How to add extra ringtone?

**Comment by opus1269** [comment]
`RingtonePreference `works as expected. Thanks!

**Comment by Gericop** [comment]
No problem. Note, however, that the artifact ID (`preference-v7-extras`) will be used to include all of the extra types available now and in the future, so if you don't want anything else but the `RingtonePreference`, you might have to change it soon (I'll post it here when the ringtone artifact is available).

Also, the latest update to the media provider (the Oreo update) that includes `RingtonePickerActivity` (which serves as the basic idea for this preference) contains a new feature to select an external ringtone by using a picker. I'll try to include it in `RingtonePreference` as well.

**Comment by Gericop** [comment]
The artifacts are being added to jCenter now, so in a couple of hours they will be available. The `RingtonePreference` will be in `com.takisoft.fix:preference-v7-ringtone:26.0.2.0`. I'll close this issue once it's available.

**Comment by Gericop** [comment]
The [`RingtonePreference`](https://github.com/Gericop/Android-Support-Preference-V7-Fix/wiki/Preference-types#ringtonepreference) is available on jCenter (also 26.0.2.0 is out for the base lib). Use 
```gradle
compile 'com.takisoft.fix:preference-v7:26.0.2.0'
compile 'com.takisoft.fix:preference-v7-ringtone:26.0.2.0'
```

Also, read the [wiki](https://github.com/Gericop/Android-Support-Preference-V7-Fix/wiki/Preference-types#ringtonepreference) for more details about the new preference.

> **Note:** `preference-v7-extra` is not out yet, so it's recommended to choose the `preference-v7-ringtone` package now.

**Comment by Gericop** [comment]
The `preference-v7-extra` artifact is available from jCenter now.

**Comment by Gericop** [comment]
@opus1269 Do you use RingtonePreference in production already? I'm asking, because I might have to change it from `String` to `StringSet`, so it could store both the URI and the name of the ringtone.

**Comment by opus1269** [comment]
Not using it in production yet. Still working through an issue. It appears that the RingtonePreference requires a permission to read tones from external storage, while the work around method I linked to above throws a warning about that but does actually list tones on external storage. Weird, but doubt if it has anything to do with your library.

**Comment by Gericop** [comment]
The `RingtoneManager` throws that warning because it needs `READ_EXTERNAL_STORAGE` permission to, well, read the external storage. If you have `WRITE_EXTERNAL_STORAGE`, it should be enough, but remember that on API 23+, you'll need to ask for either of the permissions _before_ you show the ringtone picker, otherwise it cannot read and show the external ringtones.

**Comment by Gericop** [comment]
@opus1269 Looks like I can solve it without changing from `String` to `StringSet`.
