### ISSUE TITLE
com.takisoft.fix.support.v7.preference.PreferenceScreen - cannot be resolved

### ISSUE THREAD

**Issue by anonym24** [Gericop/Android-Support-Preference-V7-Fix#68]
`android.support.v7.preference.PreferenceFragmentCompat;` is ok but why `com.takisoft.fix.support.v7.preference.PreferenceScreen;` cannot be resolved

**Comment by Gericop** [comment]
`PreferenceScreen` is still part of the original package (`android.support.v7.preference`). This library only contains classes that needed some bugfix. `PreferenceScreen` is not one of them.

**Comment by anonym24** [comment]
So how can I override onPreferenceStartScreen? It will not work:
```
import com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat;
import android.support.v7.preference.PreferenceScreen;

public class SettingsFragment extends PreferenceFragmentCompat
        implements PreferenceFragmentCompat.OnPreferenceStartScreenCallback {

    @Override
    public boolean onPreferenceStartScreen(PreferenceFragmentCompat preferenceFragmentCompat,
                                           PreferenceScreen preferenceScreen) {
        preferenceFragmentCompat.setPreferenceScreen(preferenceScreen);

        //

        return true;
    }
```
It says that `onPreferenceStartScreen` doesn't overrides anything and I can't implement this method. Works only with original `android.support.v7.preference.PreferenceFragmentCompat;`
