### ISSUE TITLE
SwitchPreferenceCompat not available on devices below API 14

### ISSUE THREAD

**Issue by Gericop** [Gericop/Android-Support-Preference-V7-Fix#69]
Apparently Google decided to just remove `SwitchCompat` from the support lib (v25.3.0) for devices below API level 14. This also means that `SwitchPreferenceCompat`, which is built on this widget, produces a fatal error on those devices. The issue [has been reported](https://code.google.com/p/android/issues/detail?id=251302), I wonder what the guys at Google will say about it...

**Comment by Gericop** [comment]
Google has fixed it already and is waiting to be released in a future version of the support lib. Hopefully they will release it soon as a hotfix and won't have to wait a month or so for the next minor version upgrade.

**Comment by Gericop** [comment]
Are you kidding me? The "fix" will be simple: in the next version (26.0.0) the min SDK level will be raised to 14 and all APIs below that will be deprecated. Now that's really messed up...

**Comment by phillat** [comment]
So what options do those of us who want to support APIs less than 14 do? Build our own custom SwitchPreference?

**Comment by Gericop** [comment]
We will see what Google does to fix it. I still hope they release a final version of the lib before dropping support of older devices. If they don't, I'll just copy the previous implementation over and use that if API level < 14.

**Comment by phillat** [comment]
I hope so too, I'm relieved, however, to know that you'll copy over the previous implementation even if official support is dropped. I'd have hated to create a custom preference. Thanks for all  your hard work.

**Comment by rubensousa** [comment]
Should be fixed in the latest 23.3.1: https://developer.android.com/topic/libraries/support-library/revisions.html#25-3-1

**Comment by Gericop** [comment]
Okay, so 25.3.0 removed the support of API 13 and lower devices, 25.3.1 added it back again, but it seems to me that they just used an earlier commit since the switch animation is not happening again... Well, I'm gonna use the custom implementation for 25.3.x, then I guess 26.0.0 drops the < API 14 support anyways, so the animation will work on its own...

**Comment by Gericop** [comment]
Released v25.3.1.0 which adds support for API 9-13 devices once again, probably for the last time, since v26.0.0 drops support for all devices below API 14.
