### ISSUE TITLE
Support lib 23.1.1

### ISSUE THREAD

**Issue by Mygod** [Gericop/Android-Support-Preference-V7-Fix#7]
https://plus.google.com/+AndroidDevelopers/posts/ebXLByBiEBU

**Comment by Gericop** [comment]
I've seen the update but haven't tested it yet, however, I don't think there's anything fixed in this update as the changelog doesn't even mention the preference lib. I'll check it out tomorrow, just to be sure.

**Comment by Gericop** [comment]
Don't see any improvements.
