### ISSUE TITLE
Support Library Revision 25.3.1

### ISSUE THREAD

**Issue by gim-** [Gericop/Android-Support-Preference-V7-Fix#70]
https://developer.android.com/topic/libraries/support-library/revisions.html#25-3-1

**Comment by Gericop** [comment]
Released v25.3.1.0.

**Comment by Khoosham** [comment]
i get the following error when i compile the latest version 25.3.1 of Android-Support-Preference-V7-Fix.
![image](https://cloud.githubusercontent.com/assets/16463632/24504991/6255c818-1569-11e7-97da-335a1f5bbd79.png)

**Comment by Gericop** [comment]
@Khoosham Did you update the Support Repository to the latest version?

**Comment by Khoosham** [comment]
working now after updating Support Repository. Thanks for the update 👍
