### ISSUE TITLE
Preferences disappear on orientation change

### ISSUE THREAD

**Issue by Pitel** [Gericop/Android-Support-Preference-V7-Fix#71]
I have a dead simple `Fragment` with just this method:
```java
@Override
public void onCreatePreferencesFix(final @Nullable Bundle savedInstanceState, final String rootKey) {
	setPreferencesFromResource(R.xml.account, rootKey);
}
```

The preferences are displayed, but when I rotate the screen, they are gone.

**Comment by Gericop** [comment]
The sample app works fine for me. You might have something related to the fragment setup, not the lib itself.

**Comment by Pitel** [comment]
Hmm, nothing special I can think of. Just a fragments which are replaced in fragment transactions.

**Comment by Gericop** [comment]
Check if you have conditions controlling the add/replace/remove operations of fragments. This usually happens if you add fragments conditionally and you check something that's not true on rotation (such as `savedInstanceState == null`).

**Comment by Pitel** [comment]
This might be it. I've just single `Activity` with `DrawerLayout` and `NavigationView` and I'm just changing fragments with code. But I left fragment management during the rotation on Android.

There is just one block of code with `savedInstanceState` in the `Activity`, for handling app shortcuts and showing proper fragment on first start:

```java
if (savedInstanceState == null) {
	switch (String.valueOf(getIntent().getAction())) {
		case "something":
			replaceFragment(new SomeFragment());
			break;
		case "somethingelse":
			replaceFragment(new SomeElseFragment());
			break;
		case "somethingcompletelydifferent":
		default:
			replaceFragment(new DifferentFragment());
	}
}
```

**Comment by Gericop** [comment]
I don't know what you're doing, but something is wrong with how you handle the fragments. Check whether `replaceFragment(...)` gets called on rotation or whether you change the layout in a way that the ID of the container doesn't match the previous one. You can check the sample app's [`MainActivity`](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/app/src/main/java/com/takisoft/preferencefix/MainActivity.java) how it just simply replaces the fragment container with the pref fragment instance once and it stays there perfectly even if you rotate the device.
