### ISSUE TITLE
java.lang.IllegalStateException: Must specify preferenceTheme in theme at android.support.v7.preference.PreferenceFragmentCompat.onCreate

### ISSUE THREAD

**Issue by anonym24** [Gericop/Android-Support-Preference-V7-Fix#72]
I'm trying to use my own theme
```
<style name="theme1" parent="Theme.AppCompat.NoActionBar">
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowShowWallpaper">true</item>
    </style>
```

but I get:
`java.lang.IllegalStateException: Must specify preferenceTheme in theme at android.support.v7.preference.PreferenceFragmentCompat.onCreate`

Can you help me?

**Comment by anonym24** [comment]
or not

<style name="theme1" parent="Theme.AppCompat.NoActionBar">
        <item name="preferenceTheme">@style/PreferenceThemeOverlay</item>
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowShowWallpaper">true</item>
    </style>


..

<activity
            android:name=".SettingsActivity" android:theme="@style/theme1"/>

I added <item name="preferenceTheme">@style/PreferenceThemeOverlay</item> but I still get this error Must specify preferenceTheme in theme at android.support.v7.preference.PreferenceFragmentCompat.onCreate 

What is wrong?

**Comment by Gericop** [comment]
So, did you solve it? 😄

**Comment by anonym24** [comment]
Seems to be working)

```
   <style name="AppTheme2" parent="Theme.AppCompat.NoActionBar">
        <item name="preferenceTheme">@style/Theme.WtfPreference</item>
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowShowWallpaper">true</item>
        <item name="colorPrimary">@color/colorActionBarSettings</item>
        <item name="colorAccent">@color/colorControlSettings</item>
        <item name="actionBarStyle">@style/MyActionBar</item>
        <item name="android:textColorPrimary">@color/colorTextPrimarySettings</item>
        <item name="android:textColorSecondary">@color/colorTextSecondarySettings</item>
    </style>

```

But how to show lines (separators) with NoAction theme?

![screenshot_2017-04-03-22-35-58-269_com android sayplayer](https://cloud.githubusercontent.com/assets/8851301/24810827/6085d5be-1bcc-11e7-877d-a272d2d0809e.png)
![screenshot_2017-04-03-22-34-48-893_com android sayplayer](https://cloud.githubusercontent.com/assets/8851301/24810828/60a5c6a8-1bcc-11e7-9738-2badc8ab8d8e.png)

**Comment by Gericop** [comment]
@anonym24 Why don't you just use one of the predefined themes, like `@style/PreferenceFixTheme.NoActionBar`, as the parent instead? Also, if your class extends `PreferenceFragmentCompatDividers` you can customize the dividers between the preferences and categories.

**Comment by anonym24** [comment]
@Gericop I'm using the same theme for other fragments, preferences is one fragment of viewpager (one activity for all fragments)

**Comment by anonym24** [comment]
oh, got it, <item name="preferenceTheme">@style/PreferenceFixTheme.NoActionBar</item>

thought about <style name="AppTheme2" parent="Theme.AppCompat.NoActionBar">

**Comment by Gericop** [comment]
Yes, instead of 
```xml
<style name="AppTheme2" parent="Theme.AppCompat.NoActionBar">
```
use
```xml
<style name="AppTheme2" parent="@style/PreferenceFixTheme.NoActionBar">
```

Also, don't forget to remove the `preferenceTheme` attribute from your `AppTheme2` style, otherwise the fixed theme will have little to no effect on the appearance.

**Comment by anonym24** [comment]
did as you said but still no dividers

**Comment by Gericop** [comment]
Check out the sample app, it shows you how to apply custom divider setup:
https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/app/src/main/java/com/takisoft/preferencefix/MyPreferenceFragment.java#L33

**Comment by anonym24** [comment]
ok I did 

```
public class SettingsFragment extends PreferenceFragmentCompatDividers

...
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, @Nullable Bundle savedInstanceState) {
        try {
            return super.onCreateView(inflater, container, savedInstanceState);
        } finally {
            // Uncomment this if you want to change the dividers' style
            setDividerPreferences(DIVIDER_PADDING_CHILD | DIVIDER_CATEGORY_AFTER_LAST | DIVIDER_CATEGORY_BETWEEN);
        }
    }
```

But seems nothing changed

**Comment by Gericop** [comment]
Clone and try the sample app with that line uncommented (but nothing else changed) and check if you see no dividers there. I think you overwrite the color / drawable of the divider somehow.

**Comment by anonym24** [comment]
It works with `parent="@style/PreferenceFixTheme.Light.NoActionBar">`
and not with `parent="@style/PreferenceFixTheme..NoActionBar">`

**Comment by Gericop** [comment]
Oh yeah, I see the problem now. You should use the `Light` variant because you're effectively doing so by setting the background to white and the text colors to some dark one, but since you didn't say it's a "light" version, the system thinks that you have a dark theme, which results in a divider that is a slightly translucent white version (due to the expected dark background).

If you, however, want to stick with the non-`Light` version, then you'll have to set the divider via `setDivider(Drawable)` after calling `setDividerPreferences(...)`. I'd not recommend this way though.

**Comment by anonym24** [comment]
Ok, thank you)
