### ISSUE TITLE
Now there is a bug in com.takisoft.fix:preference with SeekBarPreference

### ISSUE THREAD

**Issue by anonym24** [Gericop/Android-Support-Preference-V7-Fix#79]
```
<android.support.v7.preference.PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

        <android.support.v7.preference.SeekBarPreference
            android:key="test"
            android:icon="@drawable/ic_gps_fixed_black_24dp"
            android:title="SeekBarPreference"/>

</android.support.v7.preference.PreferenceScreen>
```

with `compile 'com.android.support:support-v4:25.3.1'` icon looks normally:

![screenshot_2017-05-14-15-02-47-657_com android preferencesfragment](https://cloud.githubusercontent.com/assets/8851301/26033536/1e3819a8-38b7-11e7-9230-c4ff7c9555ae.png)

with `compile 'com.takisoft.fix:preference-v7:25.3.1.0'` there is a problem with icon and right padding/margin:

![screenshot_2017-05-14-15-05-21-396_com android preferencesfragment](https://cloud.githubusercontent.com/assets/8851301/26033538/250216d0-38b7-11e7-8891-02cd6176581f.png)

at least it shows zero digit better than original library

**Comment by anonym24** [comment]
I've added an example project so you could test this bug: 

[PreferencesFragment.zip](https://github.com/Gericop/Android-Support-Preference-V7-Fix/files/999320/PreferencesFragment.zip)

**Comment by anonym24** [comment]
https://github.com/anonym24/Seekbar-Android-Support-Preference-V7-Fix

**Comment by Gericop** [comment]
Do not use fully qualified names in the XML. So instead of 
```
<android.support.v7.preference.PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

        <android.support.v7.preference.SeekBarPreference
            android:key="test"
            android:icon="@drawable/ic_gps_fixed_black_24dp"
            android:title="SeekBarPreference"/>

</android.support.v7.preference.PreferenceScreen>
```
every tag should be without the `android.support.v7.preference` qualifier:
```
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">

        <SeekBarPreference
            android:key="test"
            android:icon="@drawable/ic_gps_fixed_black_24dp"
            android:title="SeekBarPreference"/>

</PreferenceScreen>
```

**Comment by anonym24** [comment]
There is no difference actually, so it won't solve this problem with icon for seekbar (tested already)

**Comment by Gericop** [comment]
You're using the wrong theme. You have to use one of the variants of `@style/PreferenceFixTheme` as your parent theme and remove the `preferenceTheme` attribute from it. So in your case the app theme should be
```xml
<style name="AppTheme" parent="@style/PreferenceFixTheme.Light.DarkActionBar">
</style>
```

**Comment by anonym24** [comment]
Ok, changed. Also it looks like more to https://material.io/guidelines/patterns/settings.html#settings-placement

But there some differences with paddings

mine:

![screenshot_2017-05-14-16-53-18-017_com android preferencesfragment](https://cloud.githubusercontent.com/assets/8851301/26034518/9b3e2fd2-38c6-11e7-8c66-8b026b9442b8.png)

from material.io page:

<img width="360" alt="patterns_settings_sliders" src="https://cloud.githubusercontent.com/assets/8851301/26034532/a076d1de-38c6-11e7-9a9d-5a002d844a65.png">

so I think my looks a bit weird (paddings/margins)

**Comment by anonym24** [comment]
p.s. not 41, but 31

**Comment by Gericop** [comment]
You can change the `listPreferredItemPaddingLeft`/`listPreferredItemPaddingStart` and `listPreferredItemPaddingRight`/`listPreferredItemPaddingEnd` to the desired value in your theme. I haven't changed anything, the official library defines these values.

**Comment by anonym24** [comment]
ok, thanks I'll play with this values

also I'm interesting if there any possibility to change size of vector drawables so it would look the same as ordinary png icons (I set vector drawable as icon programmatically with setIcon method)

```
@Override
    public void onCreatePreferencesFix(Bundle bundle, String s) {
        addPreferencesFromResource(R.xml.preferences);

        findPreference("testSwitchPreference1").setIcon(R.drawable.warning);
    }
```

warning.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="8440dp"
    android:height="9110dp"
    android:viewportWidth="8440"
    android:viewportHeight="9110">

    <path
        android:fillColor="#000000"
        android:strokeWidth="1"
        android:pathData="M960 7940 c-163 -21 -314 -117 -394 -249 -55 -91 -76 -175 -76 -305 0 -129 13 -182
72 -301 23 -44 754 -1335 1625 -2870 1457 -2565 1590 -2795 1643 -2846 184 -179
461 -198 674 -46 33 23 71 58 86 77 30 38 3138 5612 3176 5695 38 82 54 163 54 265
0 166 -48 295 -151 405 -70 74 -134 118 -227 154 l-67 26 -3180 1 c-1749 1 -3205
-2 -3235 -6z m6370 -413 c95 -50 118 -181 54 -303 -114 -217 -3097 -5553 -3114
-5571 -30 -31 -84 -40 -126 -20 -24 12 -47 40 -87 109 -58 98 -2893 5085 -3052
5368 -115 203 -132 250 -115 319 13 54 37 82 90 105 31 13 393 15 3171 16 l3136 0
43 -23z" />
    <path
        android:fillColor="#000000"
        android:strokeWidth="1"
        android:pathData="M4128 7040 c-79 -14 -193 -75 -256 -138 -114 -112 -156 -223 -150 -391 3 -98 6
-112 40 -184 61 -127 165 -224 293 -272 92 -35 245 -36 339 -1 169 61 286 189 331
363 51 197 -37 424 -211 544 -99 68 -263 102 -386 79z" />
    <path
        android:fillColor="#000000"
        android:strokeWidth="1"
        android:pathData="M4095 5798 c-82 -29 -184 -129 -213 -208 -17 -47 -34 -221 -106 -1070 -47 -558 -86
-1033 -86 -1056 0 -100 90 -203 245 -279 113 -56 187 -75 291 -75 195 0 413 118
484 263 l30 62 -76 1050 c-65 898 -79 1058 -96 1103 -28 76 -111 162 -190 197 -86
39 -197 44 -283 13z" />
    <path
        android:fillColor="#ffd42a"
        android:strokeWidth="1"
        android:pathData="M960 7579 c-126 -50 -155 -189 -74 -347 23 -42 744 -1314 1603 -2827 1130 -1988
1574 -2760 1601 -2787 36 -35 44 -38 98 -38 45 0 67 5 93 23 28 19 290 481 1582
2797 851 1526 1560 2800 1574 2830 21 44 27 69 27 130 0 105 -36 170 -116 211 -36
19 -110 19 -3200 18 -2053 0 -3172 -4 -3188 -10z m3375 -591 c82 -17 156 -59 221
-124 72 -71 110 -146 131 -255 14 -70 14 -83 -1 -152 -43 -192 -159 -320 -335 -369
-165 -45 -323 -4 -447 117 -67 66 -104 130 -128 222 -68 262 110 526 385 572 56 9
91 7 174 -11z m-44 -1222 c123 -28 213 -113 243 -228 19 -72 160 -1975 154 -2070
-9 -128 -147 -247 -346 -297 -97 -25 -131 -26 -225 -5 -135 30 -283 115 -338 193
-55 76 -56 23 36 1111 46 553 87 1020 90 1038 22 123 116 222 243 257 61 17 76 17
143 1z" />
</vector>
```

**Comment by anonym24** [comment]
seems to be I have to play with width/height values (e.g. set to 24dp)

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="8440"
    android:viewportHeight="9110">
```
![screenshot_2017-05-14-17-31-15-630_com android preferencesfragment](https://cloud.githubusercontent.com/assets/8851301/26034821/374f7ef4-38cb-11e7-93a8-7e507243aeb4.png)

**Comment by Gericop** [comment]
Yes, that's the only solution.

**Comment by anonym24** [comment]
I guess now it can be closed.
Thanks for help
