### ISSUE TITLE
api 23 padding issue

### ISSUE THREAD

**Issue by ardadem** [Gericop/Android-Support-Preference-V7-Fix#83]
How can i solve this padding issue? I am using 26-beta2 branch.

![screenshot_1500197333](https://user-images.githubusercontent.com/13207692/28314009-ada335f4-6bc1-11e7-9746-fbaed2076b87.png)

**Comment by Gericop** [comment]
This seems like you have the `app:iconSpaceReserved="true"` attribute on your XML tags.

**Comment by ardadem** [comment]
nope, doesn't exist

**Comment by Gericop** [comment]
Do you see the same behavior in the sample app?

**Comment by ardadem** [comment]
sorry, i can't compile sample app. because always got gradle error message :\

**Comment by ardadem** [comment]
this problem doesn't exist api 24 and above.

**Comment by Gericop** [comment]
Yeah, something is messed up with the latest Gradle...

**Comment by Gericop** [comment]
Reported it to Google [here](https://issuetracker.google.com/issues/63855110), star it if you can.

**Comment by ardadem** [comment]
done

**Comment by Gericop** [comment]
@ardadem Try with the latest release v**26.0.0.0**. Also the source is compilable once again (the v26.0.0 release of the support library seems to have fixed it)

**Comment by Gericop** [comment]
I tested this on API 21 and API 24 and both seems fine with the sample app. Please test if the problem is still present on API 23. Also check if you override `listPreferredItemPaddingStart` attribute in your style because the layout of the preference uses it as a start (left) padding.

**Comment by Gericop** [comment]
@ardadem Did you solve it or is it still present?
