### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by ebenfield** [Gericop/Android-Support-Preference-V7-Fix#86]
Hi, Maybe I'm missing something obvious? I've followed step 1 in README.md and on rebuild project:

Error:Failed to resolve: com.android.support:preference-v14:26.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/ewan/AndroidStudioProjects/TM_production/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

If I clone and run gradlew I get:
"Install Android SDK Platform 26 (revision: 2)" finished.

> Configure project :preference-v7
Configuration 'compile' in project ':preference-v7' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* Where:
Script 'https://raw.githubusercontent.com/numetriclabz/jcenter/master/bintrayv.gradle' line: 26

* What went wrong:
A problem occurred evaluating script.
> /home/ewan/AndroidStudioProjects/repos/Android-Support-Preference-V7-Fix/local.properties (No such file or directory)

**Comment by Gericop** [comment]
As per the [v26.0.0 release documentation](https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-0):
> **Important:** The support libraries are now available through Google's Maven repository. You do not need to download the support repository from the SDK Manager. For more information, see [Support Library Setup](https://developer.android.com/topic/libraries/support-library/setup.html). 

This means that you need to add either of the following to your repositories in your project's `build.gradle` file:
- `maven { url "https://maven.google.com" }`
- `google()` (this one will only work if you use Android Studio 3.0+)

You can see the former in the [`build.gradle`](https://github.com/Gericop/Android-Support-Preference-V7-Fix/blob/master/build.gradle) file. _(Note that it is found in both the `buildscript` and the `allprojects` repositories as the former is for the gradle plugin itself, and the latter is for the support lib dependencies.)_

**Comment by ebenfield** [comment]
Thanks, it builds now. Will try and use tomorrow :)
