### ISSUE TITLE
findPreference(EditTextPreference).setEnabled(false) don't get correct colors

### ISSUE THREAD

**Issue by RafaG** [Gericop/Android-Support-Preference-V7-Fix#9]
Hi,

I new android developer and I not sure if is correct to post this problem here. When I disable a preference under PreferenceFragmentCompat I see the preference in the same color schema that all preferences. I have the same result in XML with android:enabled="false".

Thanks,

Rafa

**Comment by Gericop** [comment]
What API level are you trying it on? I know I've had problems on API 21 with the original themes, but looks fine to me now. Have you tried this sample? It should be good.

**Comment by RafaG** [comment]
Sorry, you are right, it work perfect.
