### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by mcxinyu** [Gericop/Android-Support-Preference-V7-Fix#94]
Error:Execution failed for task ':app:processHousiDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:preference-v14:26.1.0] AndroidManifest.xml:25:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.

**Comment by Gericop** [comment]
The latest version of the library uses the latest version of the support libraries (26.1.0 at the time of writing this). You need to either upgrade your app to use 26.1.0 support libraries or use an older version of this library. You can see the available older versions [here](https://bintray.com/gericop/maven/com.takisoft.fix%3Apreference-v7).
