### ISSUE TITLE
Error:Failed to resolve: annotationProcessor

### ISSUE THREAD

**Issue by mcxinyu** [Gericop/Android-Support-Preference-V7-Fix#95]
Error:(112, 13) Failed to resolve: com.takisoft.fix:preference-v7-extras:26.1.0.2

**Comment by Gericop** [comment]
This is not an annotation processor. Use
```gradle
compile 'com.takisoft.fix:preference-v7-extras:26.1.0.2'
```
in your build.gradle.

**Comment by mcxinyu** [comment]
使用了上面的语句，但是失败了。

Error:(471) Attribute "size" already defined with incompatible format.
Error:(467) Original attribute defined here.
Error:(6790, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6796, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6802, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6821, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(471) Attribute "size" already defined with incompatible format.
Error:(467) Original attribute defined here.
Error:(6790, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6796, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6802, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:(6821, 21) No resource found that matches the given name: attr 'headerBackground'.
Error:Execution failed for task ':app:processHousiDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by mcxinyu** [comment]
Can't these two be used at the same time?

compile 'com.takisoft.fix:preference-v7-extras:26.1.0.2'
compile 'com.takisoft.fix:preference-v7:26.1.0.2'

**Comment by Gericop** [comment]
They definitely can be used together. There's probably an attribute name collision with a different lib. What dependencies do you have?

**Comment by mcxinyu** [comment]
compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:percent:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:customtabs:26.1.0'
    //
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    //
    compile 'com.squareup.okhttp3:okhttp:3.9.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.3.0'
    //
    compile 'io.reactivex:rxjava:1.3.2'
    compile 'io.reactivex:rxandroid:1.2.1'
    //
    compile 'com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.3@aar'
    compile 'com.allenliu.versionchecklib:library:1.6.7'
    compile 'com.tbruyelle.rxpermissions:rxpermissions:0.9.4@aar'
    compile 'com.pgyersdk:sdk:2.7.0'
    //
    compile 'eu.chainfire:libsuperuser:1.0.0.201704021214'
    //
    compile 'com.yanzhenjie:recyclerview-swipe:1.1.2'
    //
    compile('com.mikepenz:aboutlibraries:5.9.7@aar') {
        transitive = true
        exclude group: 'com.android.support'
    }
    //
    compile 'com.haozhang.libary:android-slanted-textview:1.2'
    //
    compile 'com.takisoft.fix:preference-v7-extras:26.1.0.2'
    compile 'com.takisoft.fix:preference-v7:26.1.0.2'

**Comment by mcxinyu** [comment]
I tried to comment a little, but it didn't work.

**Comment by Gericop** [comment]
Yeah, this seems to be the "classic" problem where two libraries declare attributes with the same names but different formats. Unfortunately the build process is unable to just simply merge the R files together ignoring that there are fields with the same name, even though it shouldn't matter. I'll have to put prefix before the attribute names in order to make it work, but it's a pretty ugly solution and I'm just shaking my head why the Android devs decided to simply ignore namespace capabilities...

**Comment by mcxinyu** [comment]
This problem also exists with several of your other projects, for example,
`compile 'com.takisoft.fix:datetimepicker:1.0.2'`

**Comment by Gericop** [comment]
Do you know which attribute causes the trouble? I guess `compile 'com.pgyersdk:sdk:2.7.0'` is the one that has the conflicts with because gradle couldn't resolve it, and if I just removed it, no error messages appeared.

**Comment by mcxinyu** [comment]
When I upgraded the Android Studio to the latest version, the error disappeared.

**Comment by Gericop** [comment]
Fixed in v**26.1.0.3**. All custom attributes must be prefixed with `pref_`.
