### ISSUE TITLE
Feedback Question

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#99]
Hello, how to dynamic settings PreferenceCategory the title color？

**Comment by Gericop** [comment]
`PreferenceCategory` uses the accent color set by the theme of your `Activity`.

**Comment by TCQQ** [comment]
But a activity want set blue color， b activity want set red color，how do?

**Comment by Gericop** [comment]
You can set the theme per `Activity` not just per `Application`.

**Comment by TCQQ** [comment]
If so, there will be a lot of duplicate code

**Comment by Gericop** [comment]
The categories' text color should follow the accent color of the screen. The accent color of the screen is set by the theme and it applies to other things, such as widgets (the switch and checkbox items) too. You should not set different colors to different categories, and the title colors should not be different from other elements of the screen, such as checkbox items, for a constant UX.

What exactly is your use case for dynamic coloring?

**Comment by TCQQ** [comment]
Dynamically setting the color is useful because if the icon uses a color icon, if the PreferenceCategory is also colored,Interface color is not standardized

**Comment by TCQQ** [comment]
Activity color can not change, because this color represents the overall color of this application

**Comment by TCQQ** [comment]
Like this, If you can set the color dynamically, is best：

https://github.com/consp1racy/android-support-preference/blob/master/sample/src/main/java/net/xpece/android/support/preference/sample/SettingsFragment.java

**Comment by Gericop** [comment]
Use accent color tinting for your icons if you want to color them.

**Comment by TCQQ** [comment]
I do not understand, please elaborate

**Comment by TCQQ** [comment]
If modify the colorAccent color, the color control of other controls will also be modified

**Comment by TCQQ** [comment]
Can set the color of the specified preferenceCategory in the code?

**Comment by Gericop** [comment]
Released in v**27.0.0.0**. 
The `PreferenceCategory`'s color can be set from XML (using the `pref_categoryColor` attribute) and programmatically as well (`setColor(...)` and `setColorResource(...)`)

**Comment by TCQQ** [comment]
thankyou

**Comment by TCQQ** [comment]
Hi, how to change preference color ?

**Comment by Gericop** [comment]
You can do it only by changing the text color in general.

**Comment by TCQQ** [comment]
But what if the color is dynamic? Because the theme of the program allows the user to set any color, sometimes may occur black background with black text color

**Comment by Gericop** [comment]
If the background color is changed, a new theme should be applied with [`setTheme(...)`](https://developer.android.com/reference/android/app/Activity.html#setTheme(int)).
For it to be changed dynamically, the base `Preference` class should be subclassed and make use of it by every preference subclass which is just too much work and makes it harder to maintain the repo.

**Comment by TCQQ** [comment]
Theme can not add all color values, can be by code or xml dynamically changed It, because the user can also pass in the color value, for example: #FFFFFF

**Comment by Gericop** [comment]
You need two themes to handle the possible situations: light and dark. You use the light one (with dark text colors) if the background color is _light_ and use the dark one (with light text colors) if it's _dark_.

**Comment by TCQQ** [comment]
light theme：background color = white
primary color = white
account color = black
preference text color = primary color（white）

**Comment by TCQQ** [comment]
https://github.com/afollestad/material-dialogs#coloring-check-boxes
Check this library, thie library can even dynamically change the color of the check box icon, which can improve it scalability

**Comment by Gericop** [comment]
You can traverse through the whole view tree if you want and change the colors as you please. This library will not include this as it has nothing to do with preferences. I'd still suggest (if you really need this) adding two themes and switching between those depending on the lightness of the selected background color.

**Comment by TCQQ** [comment]
Ok, thank you
